SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE   PROCEDURE [dbo].[TRANS_MARGIN_FIND_BY_TRANS_ID]
    @cv_1 VARCHAR(2000) OUTPUT,
    @p_transaction_id NUMERIC
AS
BEGIN

    SET @cv_1 = NULL;

    SELECT t.TRANSACTION_MARGIN_ID,
           t.TRANSACTION_ID,
           t.TYPE_ID,
           t.FIXED_CURRENCY_CODE_ALPHA3,
           t.FIXED_AMOUNT_MINOR_UNITS,
           t.VAR_CURRENCY_CODE_ALPHA3,
           t.VAR_AMOUNT_MINOR_UNITS,
           t.FX_RATE_APPLIED_PRICING
    FROM dbo.ACC_TRANSACTION_MARGINS AS t
    WHERE t.TRANSACTION_ID = @p_transaction_id
    ORDER BY t.TYPE_ID;

    RETURN;

END;
GO
