SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE   PROCEDURE [dbo].[DESIGNATOR_LOOKUP_BY_FP]
    @cv_1 VARCHAR(2000) OUTPUT,
    @p_fee_program NVARCHAR(2000)
AS
BEGIN

    SET @cv_1 = NULL;

    SELECT DISTINCT
           CST_DESIGNATOR_ACQ_LOOKUP.RATE_TIER AS NAME
    FROM dbo.CST_DESIGNATOR_ACQ_LOOKUP
    WHERE CST_DESIGNATOR_ACQ_LOOKUP.FEE_PROGRAM = @p_fee_program
          OR @p_fee_program IS NULL
    ORDER BY CST_DESIGNATOR_ACQ_LOOKUP.RATE_TIER;

    RETURN;

END;
GO
