SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE   PROCEDURE [dbo].[PAYMENT_MES_IN_QUEUE_REMOVE]  
   @p_messsage_id numeric/* ID*/
AS 
   
   BEGIN
      DELETE dbo.ACC_PAYMENT_MESSAGES_IN_QUEUE
      FROM dbo.ACC_PAYMENT_MESSAGES_IN_QUEUE  AS pm
      WHERE pm.MESSAGE_ID = @p_messsage_id
   END
GO
