SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE   PROCEDURE [dbo].[spCostMastercardInterchangeFeeCreate]
    @accFundingSource           NCHAR(1),
    @amountCurrency             NCHAR(3),
    @approvalCode               NVARCHAR(100),
    @cabProgramExcludes         NVARCHAR(1000),
    @cabProgramInclude          NVARCHAR(100),
    @cappedMajorUnit            DECIMAL(18,8),
    @cardDataInputMode          NCHAR(1),
    @cardPresentData            TINYINT,
    @cardProgIdentifier         NCHAR(3),
    @cardholderAuthCapability   TINYINT,
    @cardholderAuthMethod       TINYINT,
    @cardholderPresentData      TINYINT,
    @corporateCardCommonData    NVARCHAR(100),
    @corporateLineItemDetail    NVARCHAR(100),
    @effectiveFrom              DATETIME2,
    @effectiveUntil             DATETIME2,
    @feePercentAsMultiplier     DECIMAL(18,8),
    @fixedCurrency              NCHAR(3),
    @fixedFeeMajorUnit          DECIMAL(18,8),
    @functionCode               NCHAR(3),
    @gcmsProductIdentifier      NCHAR(3),
    @icc                        NVARCHAR(100),
    @ird                        NCHAR(2),
    @irdDescription             NVARCHAR(100),
    @issuerCountryRegion        NVARCHAR(50),
    @maximumAmountMajorUnit     DECIMAL(18,2),
    @mccExcludes                NVARCHAR(1000),
    @mccInclude                 NCHAR(4),
    @merchantCountryRegion      NVARCHAR(50),
    @minimumAmountMajorUnit     DECIMAL(18,2),
    @mti                        NCHAR(4),
    @posTerminalInputCapability NCHAR(1),
    @processingCode             NCHAR(2),
    @productType                NVARCHAR(100),
    @score                      BIGINT,
    @serviceCode                NCHAR(1),
    @timelinessDays             BIGINT,
    @feeId                      BIGINT
AS
BEGIN
    INSERT dbo.tlkpCostMastercardInterchangeFee
    (
        EffectiveFrom,
        EffectiveUntil,
        MerchantCountryRegion,
        IssuerCountryRegion,
        Ird,
        IrdDescription,
        MinimumAmountMajorUnit,
        MaximumAmountMajorUnit,
        AmountCurrency,
        FeePercentAsMultiplier,
        FixedFeeMajorUnit,
        CappedMajorUnit,
        FixedCurrency,
        PosTerminalInputCapability,
        CardDataInputMode,
        CardholderPresentData,
        CardPresentData,
        CardholderAuthCapability,
        CardholderAuthMethod,
        Icc,
        TimelinessDays,
        ServiceCode,
        AccFundingSource,
        ProductType,
        CardProgIdentifier,
        GcmsProductIdentifier,
        Mti,
        FunctionCode,
        ProcessingCode,
        CabProgramInclude,
        CabProgramExcludes,
        MccInclude,
        MccExcludes,
        ApprovalCode,
        CorporateCardCommonData,
        CorporateLineItemDetail
    )
    VALUES
    (
        @effectiveFrom,
        @effectiveUntil,
        @merchantCountryRegion,
        @issuerCountryRegion,
        @ird,
        @irdDescription,
        @minimumAmountMajorUnit,
        @maximumAmountMajorUnit,
        @amountCurrency,
        @feePercentAsMultiplier,
        @fixedFeeMajorUnit,
        @cappedMajorUnit,
        @fixedCurrency,
        @posTerminalInputCapability,
        @cardDataInputMode,
        @cardholderPresentData,
        @cardPresentData,
        @cardholderAuthCapability,
        @cardholderAuthMethod,
        @icc,
        @timelinessDays,
        @serviceCode,
        @accFundingSource,
        @productType,
        @cardProgIdentifier,
        @gcmsProductIdentifier,
        @mti,
        @functionCode,
        @processingCode,
        @cabProgramInclude,
        @cabProgramExcludes,
        @mccInclude,
        @mccExcludes,
        @approvalCode,
        @corporateCardCommonData,
        @corporateLineItemDetail
    );
END;
GO
