SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE   PROCEDURE [dbo].[ACCTTYPE_FIND_ALL] @cv_1 VARCHAR(2000) OUTPUT
AS
BEGIN

    SET @cv_1 = NULL;

    SELECT aat.ACCOUNT_TYPE_ID,
           aat.NAME,
           aat.ROUNDING
    FROM dbo.ACC_ACCOUNT_TYPES AS aat;

    RETURN;

END;
GO
