SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE   PROCEDURE [dbo].[DESIGNATOR_TYPE_FIND]
    @cv_1 VARCHAR(2000) OUTPUT,
    @p_type_id NUMERIC
AS
BEGIN

    SET @cv_1 = NULL;

    SELECT CST_DESIGNATOR_TYPES.TYPE_ID,
           CST_DESIGNATOR_TYPES.DESCRIPTION,
           CST_DESIGNATOR_TYPES.CATEGORY_ID
    FROM dbo.CST_DESIGNATOR_TYPES
    WHERE CST_DESIGNATOR_TYPES.TYPE_ID = @p_type_id;

    RETURN;

END;
GO
