SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE   PROCEDURE [dbo].[PARTNER_RECORD_FETCH_RECENT] @cv_1 VARCHAR(2000) OUTPUT
AS
BEGIN

    SET @cv_1 = NULL;

    SELECT TOP (20)
           *
    FROM dbo.ACC_PARTNERS
    ORDER BY ACC_PARTNERS.PARTNER_ID DESC;

    RETURN;

END;
GO
