SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE   PROCEDURE [dbo].[CT_FEE_BLENDED_FIND_BY_AG]
    @cv_1 VARCHAR(2000) OUTPUT,
    @p_account_group_id NUMERIC
AS
BEGIN

    SET @cv_1 = NULL;

    SELECT ACC_CT_FEES_BLENDED.ACCOUNT_GROUP_ID,
           ACC_CT_FEES_BLENDED.PRICING_REGION_CODE,
           ACC_CT_FEES_BLENDED.FEE_DISTINGUISHER,
           ACC_CT_FEES_BLENDED.PERCENTAGE,
           ACC_CT_FEES_BLENDED.AMOUNT_MINOR_UNITS
    FROM dbo.ACC_CT_FEES_BLENDED
    WHERE ACC_CT_FEES_BLENDED.ACCOUNT_GROUP_ID = @p_account_group_id;

    RETURN;

END;
GO
