SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE   PROCEDURE [dbo].[FX_RATE_FIND_BY_ID]
    @cv_1 VARCHAR(2000) OUTPUT,
    @p_rate_id NUMERIC
AS
BEGIN

    SET @cv_1 = NULL;

    SELECT FX_RATES.RATE_ID,
           FX_RATES.RATE_DATE,
           FX_RATES.FROM_CURRENCY,
           FX_RATES.TO_CURRENCY,
           FX_RATES.RATE
    FROM dbo.FX_RATES
    WHERE FX_RATES.RATE_ID = @p_rate_id;

    RETURN;

END;
GO
