SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE   PROCEDURE [dbo].[CT_FEE_IC_FIND_BY_AG]
    @cv_1 VARCHAR(2000) OUTPUT,
    @p_account_group_id NUMERIC
AS
BEGIN

    SET @cv_1 = NULL;

    SELECT ACC_CT_FEES_IC.ACCOUNT_GROUP_ID,
           ACC_CT_FEES_IC.PERCENTAGE,
           ACC_CT_FEES_IC.AMOUNT_MINOR_UNITS
    FROM dbo.ACC_CT_FEES_IC
    WHERE ACC_CT_FEES_IC.ACCOUNT_GROUP_ID = @p_account_group_id;

    RETURN;

END;
GO
