SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE   PROCEDURE [dbo].[TRANSFER_MT_FIND_ALL] @cv_1 VARCHAR(2000) OUTPUT
AS
BEGIN

    SET @cv_1 = NULL;

    SELECT ACC_TRANSFER_METHODS.TRANSFER_METHOD_ID,
           ACC_TRANSFER_METHODS.DESCRIPTION,
           ACC_TRANSFER_METHODS.PAYMENT_TYPE_MNEMONIC
    FROM dbo.ACC_TRANSFER_METHODS;

    RETURN;

END;
GO
