SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE   PROCEDURE [dbo].[COMM_PLAN_BY_ID]
    @cv_1 VARCHAR(2000) OUTPUT,
    @p_plan_id NUMERIC
AS
BEGIN

    SET @cv_1 = NULL;

    SELECT ACC_COMMISSION_PLANS.PLAN_ID,
           ACC_COMMISSION_PLANS.PLAN_NAME,
           ACC_COMMISSION_PLANS.IS_DEFAULT,
           ACC_COMMISSION_PLANS.CRM_ID
    FROM dbo.ACC_COMMISSION_PLANS
    WHERE ACC_COMMISSION_PLANS.PLAN_ID = @p_plan_id;

    RETURN;

END;
GO
