SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE   PROCEDURE [dbo].[LATEST_REMIT_DATE_SP]
    @cv_1 VARCHAR(2000) OUTPUT,
    @p_accgrp_id NUMERIC
AS
BEGIN

    SELECT dbo.LATEST_REMIT_DATE(@p_accgrp_id) AS LATEST_REMIT_DATE;

    RETURN;

END;
GO
