SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE   PROCEDURE [dbo].[PARTNER_RECORD_FIND_ALL] @cv_1 VARCHAR(2000) OUTPUT
AS
BEGIN

    SET @cv_1 = NULL;

    SELECT ACC_PARTNERS.CRM_ID,
           ACC_PARTNERS.PARTNER_NAME,
           ACC_PARTNERS.PARTNER_OVERRIDE,
           ACC_PARTNERS.PARTNER_ID,
           ACC_PARTNERS.WEBSITE_URL,
           ACC_PARTNERS.PARTNER_TYPE_ID,
           ACC_PARTNERS.VISA_ISO_CODE,
           ACC_PARTNERS.MASTER_CARD_ISO_CODE
    FROM dbo.ACC_PARTNERS
    ORDER BY ACC_PARTNERS.PARTNER_ID DESC;

    RETURN;

END;
GO
