SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE   PROCEDURE [dbo].[PARTNER_RECORD_NON_MIGRATED] @cv_1 VARCHAR(2000) OUTPUT
AS
BEGIN

    SET @cv_1 = NULL;

    SELECT ACC_PARTNERS.CRM_ID,
           ACC_PARTNERS.PARTNER_NAME,
           ACC_PARTNERS.PARTNER_OVERRIDE,
           ACC_PARTNERS.PARTNER_ID,
           ACC_PARTNERS.WEBSITE_URL,
           ACC_PARTNERS.PARTNER_TYPE_ID,
           ACC_PARTNERS.VISA_ISO_CODE,
           ACC_PARTNERS.MASTER_CARD_ISO_CODE
    FROM dbo.ACC_PARTNERS
    WHERE ACC_PARTNERS.CRM_ID NOT IN
          (
              SELECT ISNULL(ACC_OWNERS.CRM_ID, NULL) AS expr
              FROM dbo.ACC_OWNERS
              WHERE ACC_OWNERS.OWNER_TYPE_ID != 1
          );

    RETURN;

END;
GO
