SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE   PROCEDURE [dbo].[PRICING_TIER_ALIAS_FIND_ALL] @cv_1 VARCHAR(2000) OUTPUT
AS
BEGIN

    SET @cv_1 = NULL;

    SELECT pta.PRICING_TIER_ALIAS,
           pta.PRICING_TIER_ID
    FROM dbo.ACC_PRICING_TIER_ALIASES AS pta
    ORDER BY pta.PRICING_TIER_ALIAS;

    RETURN;

END;
GO
