SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE   PROCEDURE [dbo].[spGetMaturityGrossFees]
    @cv_1         VARCHAR(2000) OUTPUT,
    @AccountId    BIGINT,
    @MaturityTime DATETIME2
AS
BEGIN
    SET NOCOUNT ON
    SET @cv_1 = NULL;

    SELECT @AccountId AS AccountId,
           ISNULL(COUNT(f.TRANSFER_ID), 0) AS NumberTransfers,
           ABS(ISNULL(SUM(f.AMOUNT_MINOR_UNITS), 0)) AS Balance 
    FROM dbo.ACC_TRANSFERS f JOIN dbo.ACC_TRANSFER_TYPES tt ON f.TRANSFER_TYPE_ID = tt.TRANSFER_TYPE_ID
    WHERE f.ACCOUNT_ID = @AccountId
      AND (tt.TRANSFER_TYPE_CLASS_ID IN (2,4)     -- FEE_VOID, FEE
          OR f.TRANSFER_TYPE_ID IN (7,52,66))    -- CHARGEBACK, SECOND CHARGEBACK, DISPUTE
      AND f.MATURITY_TIME <= @MaturityTime
      AND f.MATURITY_TRANSACTION_ID IS NULL;
END;
GO
