SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE   PROCEDURE [dbo].[HSBC_ACC_BAL_FIND]
    @cv_1 VARCHAR(2000) OUTPUT,
    @p_balance_id NUMERIC
AS
BEGIN

    SET @cv_1 = NULL;

    SELECT ACC_HSBC_ACCOUNT_BALANCES.BALANCE_ID,
           ACC_HSBC_ACCOUNT_BALANCES.ACCOUNT_ID,
           ACC_HSBC_ACCOUNT_BALANCES.BALANCE_DATE,
           ACC_HSBC_ACCOUNT_BALANCES.OPENING_BALANCE_MINOR_UNITS,
           ACC_HSBC_ACCOUNT_BALANCES.CLOSING_BALANCE_MINOR_UNITS
    FROM dbo.ACC_HSBC_ACCOUNT_BALANCES
    WHERE ACC_HSBC_ACCOUNT_BALANCES.BALANCE_ID = @p_balance_id;

    RETURN;

END;
GO
