SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE   PROCEDURE [dbo].[CURRENCY_FIND_BY_ID]
    @cv_1 VARCHAR(2000) OUTPUT,
    @p_currency_code_alpha3 VARCHAR(2000)
AS
BEGIN
    SET @cv_1 = NULL;

    SELECT c.CURRENCY_CODE_ALPHA3,
           c.DECIMAL_PLACES,
           c.DEFAULT_REMITTANCE_THRESHOLD_MINOR_UNIT
    FROM dbo.ACC_CURRENCIES AS c
    WHERE c.CURRENCY_CODE_ALPHA3 = @p_currency_code_alpha3;

    RETURN;

END;
GO
