SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE   PROCEDURE [dbo].[PRICING_TIER_ALIAS_FIND_BY_ID]
    @cv_1 VARCHAR(2000) OUTPUT,
    @p_pricing_tier_alias NVARCHAR(2000)
AS
BEGIN

    SET @cv_1 = NULL;

    SELECT pta.PRICING_TIER_ALIAS,
           pta.PRICING_TIER_ID
    FROM dbo.ACC_PRICING_TIER_ALIASES AS pta
    WHERE pta.PRICING_TIER_ALIAS = @p_pricing_tier_alias;

    RETURN;

END;
GO
