SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO


CREATE PROCEDURE [dbo].[PAYMENT_MES_OUT_QUEUE_LATEST]
   @cv_1 varchar(2000)  OUTPUT
   
AS
BEGIN
    SET @cv_1 = NULL

    SELECT TOP(1) *
    FROM ACC_PAYMENT_MESSAGES_OUT_QUEUE
    WHERE SETTLEMENT_DATE <= sysdatetime()
	AND PAYMENT_TYPE <> 'SE'
    ORDER BY MESSAGE_TIMESTAMP
END
GO
