SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE   PROCEDURE [dbo].[PRICING_TURNOVER_ALIAS_DELETE] @p_pricing_turnover_band_alias NVARCHAR(2000) /* ID*/
AS
BEGIN
    DELETE dbo.ACC_PRICING_TURNOVER_ALIASES
    FROM dbo.ACC_PRICING_TURNOVER_ALIASES AS pta
    WHERE pta.PRICING_TURNOVER_BAND_ALIAS = @p_pricing_turnover_band_alias;
END;
GO
