SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE   PROCEDURE [dbo].[TRANSFER_FIND_BY_MATURITY_TRANSACTION_ID]
    @cv_1 VARCHAR(2000) OUTPUT,
    @MaturityTransactionId BIGINT
AS
BEGIN
    SET @cv_1 = NULL;

    SELECT t.TRANSFER_ID,
           t.TRANSFER_TIME,
           t.ACCOUNT_ID,
           t.TRANSFER_TYPE_ID,
           t.AMOUNT_MINOR_UNITS,
           t.BALANCE_AFTER_MINOR_UNITS,
           t.BATCH_ID,
           t.TRANSACTION_ID,
           t.TRANSFER_METHOD_ID,
           t.MATURITY_TIME,
           t.MATURITY_TRANSACTION_ID
    FROM dbo.ACC_TRANSFERS AS t
    WHERE t.MATURITY_TRANSACTION_ID = @MaturityTransactionId
    ORDER BY t.TRANSFER_ID;

END;
GO
