SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE   PROCEDURE [dbo].[DSGN_LK_FIND_BY_TM_DIRECTION]
    @cv_1 VARCHAR(2000) OUTPUT,
    @p_transfer_method_id NUMERIC,
    @p_direction NVARCHAR(2000)
AS
BEGIN

    SET @cv_1 = NULL;

    SELECT CST_DESIGNATOR_LOOKUP.LOOKUP_ID,
           CST_DESIGNATOR_LOOKUP.TRANSFER_METHOD_ID,
           CST_DESIGNATOR_LOOKUP.DIRECTION,
           CST_DESIGNATOR_LOOKUP.DESIGNATOR_ID
    FROM dbo.CST_DESIGNATOR_LOOKUP
    WHERE CST_DESIGNATOR_LOOKUP.TRANSFER_METHOD_ID = @p_transfer_method_id
          AND CST_DESIGNATOR_LOOKUP.DIRECTION = @p_direction;

    RETURN;

END;
GO
