SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE   PROCEDURE [dbo].[BANK_STANDING_ORDER_BY_AG]
    @cv_1 VARCHAR(2000) OUTPUT,
    @p_account_group_id NUMERIC
AS
BEGIN

    SET @cv_1 = NULL;

    SELECT ACC_BANK_STANDING_ORDERS.STANDING_ORDER_ID,
           ACC_BANK_STANDING_ORDERS.ACCOUNT_GROUP_ID,
           ACC_BANK_STANDING_ORDERS.DESCRIPTION,
           ACC_BANK_STANDING_ORDERS.BANK_NAME,
           ACC_BANK_STANDING_ORDERS.BANK_ADDRESS1,
           ACC_BANK_STANDING_ORDERS.BANK_ADDRESS2,
           ACC_BANK_STANDING_ORDERS.BANK_ADDRESS3,
           ACC_BANK_STANDING_ORDERS.BANK_SORTCODE,
           ACC_BANK_STANDING_ORDERS.BANK_ACCOUNT_NUMBER,
           ACC_BANK_STANDING_ORDERS.BANK_ACCOUNTNAME,
           ACC_BANK_STANDING_ORDERS.BENEFICIARY_NAME,
           ACC_BANK_STANDING_ORDERS.BENEFICIARY_ADDRESS1,
           ACC_BANK_STANDING_ORDERS.BENEFICIARY_ADDRESS2,
           ACC_BANK_STANDING_ORDERS.BENEFICIARY_ADDRESS3,
           ACC_BANK_STANDING_ORDERS.BENEFICIARY_COUNTRY,
           ACC_BANK_STANDING_ORDERS.BENEFICIARY_REFERENCE,
           ACC_BANK_STANDING_ORDERS.BANK_SWIFT_CODE,
           ACC_BANK_STANDING_ORDERS.AGENT_BANK_SWIFT_CODE,
           ACC_BANK_STANDING_ORDERS.IBAN,
           ACC_BANK_STANDING_ORDERS.BANK_AND_BRANCH_CODE,
           ACC_BANK_STANDING_ORDERS.BSB_CODE,
           ACC_BANK_STANDING_ORDERS.HKSG_BANK_AND_BRANCH_CODE,
           ACC_BANK_STANDING_ORDERS.ABA_NUMBER,
           ACC_BANK_STANDING_ORDERS.GENERAL_ACCOUNT_NUMBER,
           ACC_BANK_STANDING_ORDERS.START_DATE,
           ACC_BANK_STANDING_ORDERS.END_DATE,
           ACC_BANK_STANDING_ORDERS.NEXT_PAYMENT_DATE,
           ACC_BANK_STANDING_ORDERS.BUSINESS_DAY_CONVENTION,
           ACC_BANK_STANDING_ORDERS.NUM_PAYMENTS,
           ACC_BANK_STANDING_ORDERS.FREQUENCY_MULTIPLIER,
           ACC_BANK_STANDING_ORDERS.FREQUENCY_UNITS,
           ACC_BANK_STANDING_ORDERS.PAYMENT_TYPE,
           ACC_BANK_STANDING_ORDERS.AMOUNT_MINOR_UNITS,
           ACC_BANK_STANDING_ORDERS.STATUS,
           ACC_BANK_STANDING_ORDERS.BANK_COUNTRY,
           ACC_BANK_STANDING_ORDERS.NEXT_SCHEDULE_DATE,
           ACC_BANK_STANDING_ORDERS.NUM_PAYMENTS_MADE,
           ACC_BANK_STANDING_ORDERS.PAYER_NAME,
           ACC_BANK_STANDING_ORDERS.PAYER_ADDRESS1,
           ACC_BANK_STANDING_ORDERS.PAYER_ADDRESS2,
           ACC_BANK_STANDING_ORDERS.PAYER_ADDRESS3,
           ACC_BANK_STANDING_ORDERS.PAYER_COUNTRY,
           ACC_BANK_STANDING_ORDERS.PAYMENT_FAILURE_EMAIL,
           ACC_BANK_STANDING_ORDERS.NUM_PAYMENTS_FAILD,
           ACC_BANK_STANDING_ORDERS.LAST_FAILURE_DATE,
           ACC_BANK_STANDING_ORDERS.ROUTING_TRANSIT_NUMBER,
           ACC_BANK_STANDING_ORDERS.SA_BANK_BRANCH_CODE,
           ACC_BANK_STANDING_ORDERS.PAY_ALL
    FROM dbo.ACC_BANK_STANDING_ORDERS
    WHERE ACC_BANK_STANDING_ORDERS.ACCOUNT_GROUP_ID = @p_account_group_id;

    RETURN;

END;
GO
