SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE   PROCEDURE [dbo].[TRANSFER_FIND_BALANCE_BY_BATCH]
    @cv_1 VARCHAR(2000) OUTPUT,
    @AccountId BIGINT,
    @MaturityTransactionId BIGINT
AS
BEGIN
    SET @cv_1 = NULL;

    SELECT ISNULL(SUM(ACC_TRANSFERS.AMOUNT_MINOR_UNITS), 0) AS id
    FROM dbo.ACC_TRANSFERS
    WHERE ACCOUNT_ID = @AccountId
      AND MATURITY_TRANSACTION_ID = @MaturityTransactionId;

END;
GO
