SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE   PROCEDURE [dbo].[HSBC_ACC_FIND_ALL]


    @cv_1 VARCHAR(2000) OUTPUT
AS
BEGIN

    SET @cv_1 = NULL;

    SELECT ACC_HSBC_ACCOUNTS.ACCOUNT_ID,
           ACC_HSBC_ACCOUNTS.CURRENCY_CODE_ALPHA3,
           ACC_HSBC_ACCOUNTS.ACCOUNT_NUMBER,
           ACC_HSBC_ACCOUNTS.DESCRIPTION,
           ACC_HSBC_ACCOUNTS.STATEMENT_ENABLED
    FROM dbo.ACC_HSBC_ACCOUNTS;

    RETURN;

END;
GO
