SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE   PROCEDURE [dbo].[EVTPOST_OBTAIN_TXN_ASSOC_ID] @cv_1 VARCHAR(2000) OUTPUT
AS
BEGIN

    SET @cv_1 = NULL;

    SELECT NEXT VALUE FOR dbo.TXN_ASSOCIATION_SEQUENCE AS ID;

END;
GO
