SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE   PROCEDURE [dbo].[COMM_POINT_BY_ID]
    @cv_1 VARCHAR(2000) OUTPUT,
    @p_point_id NUMERIC
AS
BEGIN

    SET @cv_1 = NULL;

    SELECT ACC_COMMISSION_POINTS.POINT_ID,
           ACC_COMMISSION_POINTS.EVENT_TYPE_ID,
           ACC_COMMISSION_POINTS.FEE_DISTINGUISHER,
           ACC_COMMISSION_POINTS.FIXED_AMOUNT_MINOR_UNITS,
           ACC_COMMISSION_POINTS.FIXED_CURRENCY_CODE_ALPHA3,
           ACC_COMMISSION_POINTS.VARIABLE_PERCENTAGE,
           ACC_COMMISSION_POINTS.COMMISSION_PLAN_ID,
           ACC_COMMISSION_POINTS.SPLIT_PERCENTAGE,
           ACC_COMMISSION_POINTS.SCHEME_REGION_CODE
    FROM dbo.ACC_COMMISSION_POINTS
    WHERE ACC_COMMISSION_POINTS.POINT_ID = @p_point_id;

    RETURN;

END;
GO
