SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE   PROCEDURE [dbo].[HSBC_ACC_FIND]
    @cv_1 VARCHAR(2000) OUTPUT,
    @p_account_id NUMERIC
AS
BEGIN

    SET @cv_1 = NULL;

    SELECT ACC_HSBC_ACCOUNTS.ACCOUNT_ID,
           ACC_HSBC_ACCOUNTS.CURRENCY_CODE_ALPHA3,
           ACC_HSBC_ACCOUNTS.ACCOUNT_NUMBER,
           ACC_HSBC_ACCOUNTS.DESCRIPTION,
           ACC_HSBC_ACCOUNTS.STATEMENT_ENABLED
    FROM dbo.ACC_HSBC_ACCOUNTS
    WHERE ACC_HSBC_ACCOUNTS.ACCOUNT_ID = @p_account_id;

    RETURN;

END;
GO
