SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE   PROCEDURE [dbo].[AUDIT_EVENT_TYPE_BY_ID]
    @cv_1 VARCHAR(2000) OUTPUT,
    @p_audit_event_type_id NUMERIC /* ID*/
AS
BEGIN

    SET @cv_1 = NULL;

    SELECT ACC_AUDIT_EVENT_TYPES.AUDIT_EVENT_TYPE_ID,
           ACC_AUDIT_EVENT_TYPES.NAME
    FROM dbo.ACC_AUDIT_EVENT_TYPES
    WHERE ACC_AUDIT_EVENT_TYPES.AUDIT_EVENT_TYPE_ID = @p_audit_event_type_id;

    RETURN;

END;
GO
