SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE   PROCEDURE [dbo].[BANK_PAYEE_BY_AG_AND_NAME]
    @cv_1 VARCHAR(2000) OUTPUT,
    @p_account_group_id NUMERIC,
    @p_beneficiary_name NVARCHAR(2000)
AS
BEGIN

    SET @cv_1 = NULL;

    SELECT ACC_BANK_PAYEES.PAYEE_ID,
           ACC_BANK_PAYEES.ACCOUNT_GROUP_ID,
           ACC_BANK_PAYEES.BANK_NAME,
           ACC_BANK_PAYEES.BANK_ADDRESS1,
           ACC_BANK_PAYEES.BANK_ADDRESS2,
           ACC_BANK_PAYEES.BANK_ADDRESS3,
           ACC_BANK_PAYEES.BANK_SORTCODE,
           ACC_BANK_PAYEES.BANK_ACCOUNTNAME,
           ACC_BANK_PAYEES.BENEFICIARY_ADDRESS1,
           ACC_BANK_PAYEES.BENEFICIARY_ADDRESS2,
           ACC_BANK_PAYEES.BENEFICIARY_ADDRESS3,
           ACC_BANK_PAYEES.BENEFICIARY_REFERENCE,
           ACC_BANK_PAYEES.BANK_ACCOUNT_NUMBER,
           ACC_BANK_PAYEES.BANK_SWIFT_CODE,
           ACC_BANK_PAYEES.BANK_AND_BRANCH_CODE,
           ACC_BANK_PAYEES.BSB_CODE,
           ACC_BANK_PAYEES.HKSG_BANK_AND_BRANCH_CODE,
           ACC_BANK_PAYEES.IBAN,
           ACC_BANK_PAYEES.ABA_NUMBER,
           ACC_BANK_PAYEES.GENERAL_ACCOUNT_NUMBER,
           ACC_BANK_PAYEES.BENEFICIARY_NAME,
           ACC_BANK_PAYEES.AGENT_BANK_SWIFT_CODE,
           ACC_BANK_PAYEES.BENEFICIARY_COUNTRY,
           ACC_BANK_PAYEES.BANK_COUNTRY,
           ACC_BANK_PAYEES.ROUTING_TRANSIT_NUMBER,
           ACC_BANK_PAYEES.SA_BANK_BRANCH_CODE
    FROM dbo.ACC_BANK_PAYEES
    WHERE ACC_BANK_PAYEES.ACCOUNT_GROUP_ID = @p_account_group_id
          AND ACC_BANK_PAYEES.BENEFICIARY_NAME = @p_beneficiary_name;

    RETURN;

END;
GO
