SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE   PROCEDURE [dbo].[TRANSFER_FIND_BALANCE_BY_DATE]
    @cv_1 VARCHAR(2000) OUTPUT,
    @AccountId BIGINT,
    @BatchDate DATETIME2
AS
BEGIN
    DECLARE @NextDate DATETIME2;

    SET @cv_1 = NULL;
    SET @NextDate = DATEADD(day, 1, @BatchDate)

    SELECT ISNULL(SUM(ACC_TRANSFERS.AMOUNT_MINOR_UNITS), 0) AS id
    FROM dbo.ACC_TRANSFERS
    WHERE ACCOUNT_ID = @AccountId
      AND MATURITY_TIME IS NOT NULL
      AND MATURITY_TRANSACTION_ID IS NULL
      AND MATURITY_TIME >= @BatchDate
      AND MATURITY_TIME < @NextDate;

END;
GO
