SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE   PROCEDURE [dbo].[HSBC_ACC_MAP_FIND_ALL] @cv_1 VARCHAR(2000) OUTPUT
AS
BEGIN

    SET @cv_1 = NULL;

    SELECT ACC_HSBC_ACCOUNT_MAPPINGS.ACCOUNT_MAPPING_ID,
           ACC_HSBC_ACCOUNT_MAPPINGS.CURRENCY_CODE_ALPHA3,
           ACC_HSBC_ACCOUNT_MAPPINGS.SORT_CODE,
           ACC_HSBC_ACCOUNT_MAPPINGS.TRANSFER_TYPE_ID,
           ACC_HSBC_ACCOUNT_MAPPINGS.TRANSFER_METHOD_ID,
           ACC_HSBC_ACCOUNT_MAPPINGS.ACCOUNT_ID,
           ACC_HSBC_ACCOUNT_MAPPINGS.INCL_EXCL
    FROM dbo.ACC_HSBC_ACCOUNT_MAPPINGS
    ORDER BY ACC_HSBC_ACCOUNT_MAPPINGS.ACCOUNT_MAPPING_ID;

    RETURN;

END;
GO
