SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE   PROCEDURE [dbo].[PRICING_POLICY_FIND]
    @cv_1 VARCHAR(2000) OUTPUT,
    @p_pricing_policy_id NUMERIC
AS
BEGIN

    SET @cv_1 = NULL;

    SELECT ACC_PRICING_POLICY.PRICING_POLICY_ID,
           ACC_PRICING_POLICY.NAME
    FROM dbo.ACC_PRICING_POLICY
    WHERE ACC_PRICING_POLICY.PRICING_POLICY_ID = @p_pricing_policy_id;

    RETURN;

END;
GO
