SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE   PROCEDURE [dbo].[COMM_TEMP_FIND_ALL] @cv_1 VARCHAR(2000) OUTPUT
AS
BEGIN

    SET @cv_1 = NULL;

    SELECT ACC_COMMISSION_TEMPLATES.TEMPLATE_ID,
           ACC_COMMISSION_TEMPLATES.EVENT_TYPE_ID,
           ACC_COMMISSION_TEMPLATES.FEE_DISTINGUISHER,
           ACC_COMMISSION_TEMPLATES.FIXED_AMOUNT_MINOR_UNITS,
           ACC_COMMISSION_TEMPLATES.FIXED_CURRENCY_CODE_ALPHA3,
           ACC_COMMISSION_TEMPLATES.VARIABLE_PERCENTAGE,
           ACC_COMMISSION_TEMPLATES.SPLIT_PERCENTAGE,
           ACC_COMMISSION_TEMPLATES.SCHEME_REGION_CODE
    FROM dbo.ACC_COMMISSION_TEMPLATES;

    RETURN;

END;
GO
