SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE   PROCEDURE [dbo].[BULK_PAYMENT_BATCH_DELETE]  
   @p_batch_id numeric
AS 
   
   BEGIN
      DELETE dbo.ACC_BULK_PAYMENT_BATCHES
      FROM dbo.ACC_BULK_PAYMENT_BATCHES  AS b
      WHERE b.BATCH_ID = @p_batch_id
   END
GO
