SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE   PROCEDURE [dbo].[SESSION_JSF_FIND_BY_UUID]
    @cv_1 VARCHAR(2000) OUTPUT,
    @p_session_uuid NVARCHAR(36)
AS
BEGIN

    SET @cv_1 = NULL;

    SELECT ACC_SESSIONS_JSF.SESSION_UUID,
           ACC_SESSIONS_JSF.SESSION_STATE,
           ACC_SESSIONS_JSF.EXPIRY_TIME,
           ACC_SESSIONS_JSF.ACCESS_COUNT
    FROM dbo.ACC_SESSIONS_JSF
    WHERE ACC_SESSIONS_JSF.SESSION_UUID = @p_session_uuid;

    RETURN;

END;
GO
