SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE   PROCEDURE [dbo].[DESIGNATOR_LOOKUP_BY_CT]
    @cv_1 VARCHAR(2000) OUTPUT,
    @p_card_type NVARCHAR(2000)
AS
BEGIN

    SET @cv_1 = NULL;

    SELECT DISTINCT
           CST_DESIGNATOR_ACQ_LOOKUP.FEE_PROGRAM AS NAME
    FROM dbo.CST_DESIGNATOR_ACQ_LOOKUP
    WHERE CST_DESIGNATOR_ACQ_LOOKUP.FEE_PROGRAM LIKE @p_card_type;

    RETURN;

END;
GO
