SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE   PROCEDURE [dbo].[BULK_PAYMENT_TR_UPDATE]
    @p_account_group_id NUMERIC,
    @p_amount_minor_units NUMERIC,
    @p_aba_number NVARCHAR(2000),
    @p_agent_bank_swift_code NVARCHAR(2000),
    @p_bank_accountname NVARCHAR(2000),
    @p_bank_account_number NVARCHAR(2000),
    @p_bank_address1 NVARCHAR(2000),
    @p_bank_address2 NVARCHAR(2000),
    @p_bank_address3 NVARCHAR(2000),
    @p_bank_and_branch_code NVARCHAR(2000),
    @p_bank_country VARCHAR(2000),
    @p_bank_name NVARCHAR(2000),
    @p_bank_sortcode NVARCHAR(2000),
    @p_bank_swift_code NVARCHAR(2000),
    @p_beneficiary_address1 NVARCHAR(2000),
    @p_beneficiary_address2 NVARCHAR(2000),
    @p_beneficiary_address3 NVARCHAR(2000),
    @p_beneficiary_country VARCHAR(2000),
    @p_beneficiary_name NVARCHAR(2000),
    @p_beneficiary_reference NVARCHAR(2000),
    @p_bsb_code NVARCHAR(2000),
    @p_general_account_number NVARCHAR(2000),
    @p_hksg_bank_and_branch_code NVARCHAR(2000),
    @p_iban NVARCHAR(2000),
    @p_routing_transit_number NVARCHAR(2000),
    @p_sa_bank_branch_code NVARCHAR(2000),
    @p_payer_address1 NVARCHAR(2000),
    @p_payer_address2 NVARCHAR(2000),
    @p_payer_address3 NVARCHAR(2000),
    @p_payer_country VARCHAR(2000),
    @p_payer_name NVARCHAR(2000),
    @p_batch_id NUMERIC,
    @p_comments NVARCHAR(2000),
    @p_cover_all_payment_fees VARCHAR(2000),
    @p_payment_currency VARCHAR(2000),
    @p_payment_date DATETIME2(6),
    @p_payment_type VARCHAR(2000),
    @p_status VARCHAR(2000),
    @p_bulk_transaction_id NUMERIC
AS
BEGIN
    UPDATE dbo.ACC_BULK_PAYMENT_TRANSACTIONS
    SET BULK_TRANSACTION_ID = @p_bulk_transaction_id,
        BATCH_ID = @p_batch_id,
        COMMENTS = @p_comments,
        PAYMENT_CURRENCY = @p_payment_currency,
        PAYMENT_DATE = @p_payment_date,
        ACCOUNT_GROUP_ID = @p_account_group_id,
        BANK_NAME = @p_bank_name,
        BANK_ADDRESS1 = @p_bank_address1,
        BANK_ADDRESS2 = @p_bank_address2,
        BANK_ADDRESS3 = @p_bank_address3,
        BANK_COUNTRY = @p_bank_country,
        BENEFICIARY_NAME = @p_beneficiary_name,
        BENEFICIARY_ADDRESS1 = @p_beneficiary_address1,
        BENEFICIARY_ADDRESS2 = @p_beneficiary_address2,
        BENEFICIARY_ADDRESS3 = @p_beneficiary_address3,
        BENEFICIARY_COUNTRY = @p_beneficiary_country,
        BENEFICIARY_REFERENCE = @p_beneficiary_reference,
        BANK_ACCOUNTNAME = @p_bank_accountname,
        BANK_SORTCODE = @p_bank_sortcode,
        BANK_ACCOUNT_NUMBER = @p_bank_account_number,
        BANK_SWIFT_CODE = @p_bank_swift_code,
        BANK_AND_BRANCH_CODE = @p_bank_and_branch_code,
        BSB_CODE = @p_bsb_code,
        HKSG_BANK_AND_BRANCH_CODE = @p_hksg_bank_and_branch_code,
        IBAN = @p_iban,
        ABA_NUMBER = @p_aba_number,
        GENERAL_ACCOUNT_NUMBER = @p_general_account_number,
        AGENT_BANK_SWIFT_CODE = @p_agent_bank_swift_code,
        PAYMENT_TYPE = @p_payment_type,
        AMOUNT_MINOR_UNITS = @p_amount_minor_units,
        STATUS = @p_status,
        PAYER_NAME = @p_payer_name,
        PAYER_ADDRESS1 = @p_payer_address1,
        PAYER_ADDRESS2 = @p_payer_address2,
        PAYER_ADDRESS3 = @p_payer_address3,
        PAYER_COUNTRY = @p_payer_country,
        COVER_ALL_PAYMENT_FEES = @p_cover_all_payment_fees,
        ROUTING_TRANSIT_NUMBER = @p_routing_transit_number,
        SA_BANK_BRANCH_CODE = @p_sa_bank_branch_code
    FROM dbo.ACC_BULK_PAYMENT_TRANSACTIONS AS b
    WHERE b.BULK_TRANSACTION_ID = @p_bulk_transaction_id;
END;
GO
