SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE   PROCEDURE [dbo].[TRANSFER_TP_FIND_ALL] @cv_1 VARCHAR(2000) OUTPUT
AS
BEGIN

    SET @cv_1 = NULL;

    SELECT ACC_TRANSFER_TYPES.TRANSFER_TYPE_ID,
           ACC_TRANSFER_TYPES.NAME,
           ACC_TRANSFER_TYPES.DESCRIPTION
    FROM dbo.ACC_TRANSFER_TYPES;

    RETURN;

END;
GO
