SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE   PROCEDURE [dbo].[DESIGNATOR_LOOKUP_BY_ID]
    @cv_1 VARCHAR(2000) OUTPUT,
    @p_lookup_id NUMERIC
AS
BEGIN

    SET @cv_1 = NULL;

    SELECT CST_DESIGNATOR_ACQ_LOOKUP.LOOKUP_ID,
           CST_DESIGNATOR_ACQ_LOOKUP.FEE_PROGRAM,
           CST_DESIGNATOR_ACQ_LOOKUP.RATE_TIER,
           CST_DESIGNATOR_ACQ_LOOKUP.INTERCHANGE_DESCRIPTION,
           CST_DESIGNATOR_ACQ_LOOKUP.DESIGNATOR_ID
    FROM dbo.CST_DESIGNATOR_ACQ_LOOKUP
    WHERE CST_DESIGNATOR_ACQ_LOOKUP.LOOKUP_ID = @p_lookup_id;

    RETURN;

END;
GO
