SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE   PROCEDURE [dbo].[PAYMENT_SOURCE_FIND]
    @cv_1 VARCHAR(2000) OUTPUT,
    @p_id NUMERIC /* ID1*/
AS
BEGIN

    SET @cv_1 = NULL;

    SELECT ps.BULK_PAYMENT_SOURCE_ID,
           ps.BULK_PAYMENT_SOURCE_NAME
    FROM dbo.ACC_PAYMENT_SOURCES AS ps
    WHERE ps.BULK_PAYMENT_SOURCE_ID = @p_id;

    RETURN;

END;
GO
