SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE   PROCEDURE [dbo].[GEN_MES_OUT_QUEUE_REMOVE]  
   @p_messsage_id numeric/* ID*/
AS 
   
   BEGIN
      DELETE dbo.ACC_GENERIC_MESSAGES_OUT_QUEUE
      FROM dbo.ACC_GENERIC_MESSAGES_OUT_QUEUE  AS gm
      WHERE gm.MESSAGE_ID = @p_messsage_id
   END
GO
