SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE   PROCEDURE [dbo].[PRICING_TURNOVER_ALIAS_FINDALL] @cv_1 VARCHAR(2000) OUTPUT
AS
BEGIN

    SET @cv_1 = NULL;

    SELECT pta.PRICING_TURNOVER_BAND_ALIAS,
           pta.PRICING_TURNOVER_BAND_ID
    FROM dbo.ACC_PRICING_TURNOVER_ALIASES AS pta
    ORDER BY pta.PRICING_TURNOVER_BAND_ALIAS;

    RETURN;

END;
GO
