SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE   PROCEDURE [dbo].[SEPA_ENABLED_CODE_BY_PART]
    @cv_1 VARCHAR(2000) OUTPUT,
    @p_bic_code NVARCHAR(2000)
AS
BEGIN

    SET @cv_1 = NULL;

    SELECT ACC_SEPA_ENABLED_CODES.BIC_CODE
    FROM dbo.ACC_SEPA_ENABLED_CODES
    WHERE ACC_SEPA_ENABLED_CODES.BIC_CODE LIKE @p_bic_code;

    RETURN;

END;
GO
