SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE   PROCEDURE [dbo].[TEMPLATE_BL_FIND_BY_TURNOVER]
    @cv_1 VARCHAR(2000) OUTPUT,
    @p_pricing_turnover_band_id NUMERIC
AS
BEGIN

    SET @cv_1 = NULL;

    SELECT t.TEMPLATE_BLENDED_ID,
           t.REGION_CODE,
           t.AMOUNT_MINOR_UNITS,
           t.PERCENTAGE,
           t.PRICING_TURNOVER_BAND_ID,
           t.TRANSACTION_CATEGORY_CODE,
           t.CARD_CATEGORY_CODE
    FROM dbo.ACC_PRICING_TEMPLATES_BLENDED AS t
    WHERE t.PRICING_TURNOVER_BAND_ID = @p_pricing_turnover_band_id;

    RETURN;

END;
GO
