SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE   PROCEDURE [dbo].[COMM_POINT_UPDATE_VARIABLE]
    @cv_1 VARCHAR(2000) OUTPUT,
    @p_point_id NUMERIC,
    @p_fixed_amount NUMERIC,
    @p_fixed_amount_cuurency NVARCHAR(2000),
    @p_variable_percentage NUMERIC (18,4),
    @p_split_percentage NUMERIC (18, 2)
AS
BEGIN

    SET @cv_1 = NULL;

    UPDATE dbo.ACC_COMMISSION_POINTS
    SET FIXED_AMOUNT_MINOR_UNITS = @p_fixed_amount,
        FIXED_CURRENCY_CODE_ALPHA3 = @p_fixed_amount_cuurency,
        VARIABLE_PERCENTAGE = @p_variable_percentage,
        SPLIT_PERCENTAGE = @p_split_percentage
    WHERE ACC_COMMISSION_POINTS.POINT_ID = @p_point_id;

    /* Return current state of commission point.*/
    SELECT ACC_COMMISSION_POINTS.POINT_ID,
           ACC_COMMISSION_POINTS.EVENT_TYPE_ID,
           ACC_COMMISSION_POINTS.FEE_DISTINGUISHER,
           ACC_COMMISSION_POINTS.FIXED_AMOUNT_MINOR_UNITS,
           ACC_COMMISSION_POINTS.FIXED_CURRENCY_CODE_ALPHA3,
           ACC_COMMISSION_POINTS.VARIABLE_PERCENTAGE,
           ACC_COMMISSION_POINTS.COMMISSION_PLAN_ID,
           ACC_COMMISSION_POINTS.SPLIT_PERCENTAGE,
           ACC_COMMISSION_POINTS.SCHEME_REGION_CODE
    FROM dbo.ACC_COMMISSION_POINTS
    WHERE ACC_COMMISSION_POINTS.POINT_ID = @p_point_id;

END;
GO
