SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE   PROCEDURE [dbo].[ACQUIRING_FEE_BY_AG]
    @cv_1 VARCHAR(2000) OUTPUT,
    @p_account_group_id NUMERIC
AS
BEGIN

    SET @cv_1 = NULL;

    SELECT ACC_ACQUIRING_FEES.FEE_ID,
           ACC_ACQUIRING_FEES.ACCOUNT_GROUP_ID,
           ACC_ACQUIRING_FEES.EVENT_TYPE_ID,
           ACC_ACQUIRING_FEES.PERCENTAGE,
           ACC_ACQUIRING_FEES.AMOUNT_MINOR_UNITS
    FROM dbo.ACC_ACQUIRING_FEES
    WHERE ACC_ACQUIRING_FEES.ACCOUNT_GROUP_ID = @p_account_group_id;

    RETURN;

END;
GO
