SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE   PROCEDURE [dbo].[COMM_TEMP_FIND_BY_EVENT]
    @cv_1 VARCHAR(2000) OUTPUT,
    @p_event_type_id NUMERIC
AS
BEGIN

    SET @cv_1 = NULL;

    SELECT ACC_COMMISSION_TEMPLATES.TEMPLATE_ID,
           ACC_COMMISSION_TEMPLATES.EVENT_TYPE_ID,
           ACC_COMMISSION_TEMPLATES.FEE_DISTINGUISHER,
           ACC_COMMISSION_TEMPLATES.FIXED_AMOUNT_MINOR_UNITS,
           ACC_COMMISSION_TEMPLATES.FIXED_CURRENCY_CODE_ALPHA3,
           ACC_COMMISSION_TEMPLATES.VARIABLE_PERCENTAGE,
           ACC_COMMISSION_TEMPLATES.SPLIT_PERCENTAGE,
           ACC_COMMISSION_TEMPLATES.SCHEME_REGION_CODE
    FROM dbo.ACC_COMMISSION_TEMPLATES
    WHERE ACC_COMMISSION_TEMPLATES.EVENT_TYPE_ID = @p_event_type_id;

    RETURN;

END;
GO
