SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE   PROCEDURE [dbo].[PAYMENT_MES_IN_FIND_ALL] @cv_1 VARCHAR(2000) OUTPUT
AS
BEGIN

    SET @cv_1 = NULL;

    SELECT ACC_PAYMENT_MESSAGES_IN.MESSAGE_ID,
           ACC_PAYMENT_MESSAGES_IN.MESSAGE_TIMESTAMP,
           ACC_PAYMENT_MESSAGES_IN.PAYMENT_TYPE,
           ACC_PAYMENT_MESSAGES_IN.HEADER_MESSAGE_ID,
           ACC_PAYMENT_MESSAGES_IN.END_TO_END_ID,
           ACC_PAYMENT_MESSAGES_IN.TRANSACTION_ID,
           ACC_PAYMENT_MESSAGES_IN.PAYER_NAME,
           ACC_PAYMENT_MESSAGES_IN.PAYER_ACCOUNT_ID,
           ACC_PAYMENT_MESSAGES_IN.PAYER_ADDRESS_1,
           ACC_PAYMENT_MESSAGES_IN.PAYER_ADDRESS_2,
           ACC_PAYMENT_MESSAGES_IN.PAYER_ADDRESS_3,
           ACC_PAYMENT_MESSAGES_IN.PAYEE_NAME,
           ACC_PAYMENT_MESSAGES_IN.PAYEE_ACCOUNT_ID,
           ACC_PAYMENT_MESSAGES_IN.PAYEE_ADDRESS_1,
           ACC_PAYMENT_MESSAGES_IN.PAYEE_ADDRESS_2,
           ACC_PAYMENT_MESSAGES_IN.PAYEE_ADDRESS_3,
           ACC_PAYMENT_MESSAGES_IN.AMOUNT_MINOR_UNITS,
           ACC_PAYMENT_MESSAGES_IN.CURRENCY_CODE_ALPHA3,
           ACC_PAYMENT_MESSAGES_IN.MESSAGE_STATUS,
           ACC_PAYMENT_MESSAGES_IN.MESSAGE_TEXT,
           ACC_PAYMENT_MESSAGES_IN.PAYMENT_OR_RETURN,
           ACC_PAYMENT_MESSAGES_IN.PAYER_SORT_CODE,
           ACC_PAYMENT_MESSAGES_IN.PAYEE_SORT_CODE,
           ACC_PAYMENT_MESSAGES_IN.INSTRUCTION_FOR_NEXT_AGENT,
           ACC_PAYMENT_MESSAGES_IN.PAYEE_ACCOUNT_ID_TYPE,
           ACC_PAYMENT_MESSAGES_IN.PAYER_ACCOUNT_ID_TYPE,
           ACC_PAYMENT_MESSAGES_IN.PAYER_AGENT_ID,
           ACC_PAYMENT_MESSAGES_IN.PAYER_AGENT_ID_TYPE,
           ACC_PAYMENT_MESSAGES_IN.SETTLEMENT_DATE,
           ACC_PAYMENT_MESSAGES_IN.MESSAGE_TRANSACTION_ID,
           ACC_PAYMENT_MESSAGES_IN.REFERENCE_FOR_BENEFICIARY,
           ACC_PAYMENT_MESSAGES_IN.RMT_INF_ADDTL,
           ACC_PAYMENT_MESSAGES_IN.RMT_INF_USTRD,
           ACC_PAYMENT_MESSAGES_IN.INTERMEDIARY_AGENT_ID,
           ACC_PAYMENT_MESSAGES_IN.INTERMEDIARY_AGENT_ID_TYPE
    FROM dbo.ACC_PAYMENT_MESSAGES_IN
    ORDER BY ACC_PAYMENT_MESSAGES_IN.MESSAGE_TIMESTAMP;

    RETURN;

END;
GO
