SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE   PROCEDURE [dbo].[CONCURRENT_REPORT_REMOVE] @p_report_name NVARCHAR(2000)
AS
BEGIN
    DELETE dbo.ACC_CONCURRENT_REPORTS
    WHERE ACC_CONCURRENT_REPORTS.REPORT_NAME = @p_report_name;
END;
GO
