SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE   PROCEDURE [dbo].[CT_TMPL_BL_FIND_BY_TURNOVER]
    @cv_1 VARCHAR(2000) OUTPUT,
    @p_pricing_turnover_band_id NUMERIC
AS
BEGIN

    SET @cv_1 = NULL;

    SELECT t.PRICING_TURNOVER_BAND_ID,
           t.PRICING_REGION_CODE,
           t.FEE_DISTINGUISHER,
           t.PERCENTAGE,
           t.AMOUNT_MINOR_UNITS
    FROM dbo.ACC_CT_PRICING_TMPLS_BLENDED AS t
    WHERE t.PRICING_TURNOVER_BAND_ID = @p_pricing_turnover_band_id;

    RETURN;

END;
GO
