SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE   PROCEDURE [dbo].[PROCESSOR_RECORD_BY_ID]
    @cv_1 VARCHAR(2000) OUTPUT,
    @p_acc_processor_id NUMERIC
AS
BEGIN

    SET @cv_1 = NULL;

    SELECT ACC_PROCESSOR_RECORDS.ACC_PROCESSOR_ID,
           ACC_PROCESSOR_RECORDS.PROCESSOR_NAME,
           ACC_PROCESSOR_RECORDS.PROCESS_TIMESTAMP,
           ACC_PROCESSOR_RECORDS.USERNAME,
           ACC_PROCESSOR_RECORDS.PROCESS_LOG
    FROM dbo.ACC_PROCESSOR_RECORDS
    WHERE ACC_PROCESSOR_RECORDS.ACC_PROCESSOR_ID = @p_acc_processor_id;

    RETURN;

END;
GO
