SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE   PROCEDURE [dbo].[CARD_TYPE_FIND_ALL] @cv_1 VARCHAR(2000) OUTPUT
AS
BEGIN

    SET @cv_1 = NULL;

    SELECT ACC_CARD_TYPES.CARD_TYPE_ID,
           ACC_CARD_TYPES.NAME,
           ACC_CARD_TYPES.CARD_CATEGORY_CODE
    FROM dbo.ACC_CARD_TYPES;

    RETURN;

END;
GO
