SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE   PROCEDURE [dbo].[SEPA_ENABLED_CODE_CREATE] @p_bic_code NVARCHAR(2000)
AS
BEGIN
    INSERT dbo.ACC_SEPA_ENABLED_CODES
    (
        BIC_CODE
    )
    VALUES
    (@p_bic_code);
END;
GO
