SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE   PROCEDURE [dbo].[AUDIT_EVENT_FILTERED]
    @cv_1 VARCHAR(2000) OUTPUT,
    @p_start_date DATETIME2(6),
    @p_end_date DATETIME2(6),
    @p_audit_event_type_id NUMERIC
AS
BEGIN

    SET @cv_1 = NULL;

    SELECT ACC_AUDIT_EVENTS.AUDIT_EVENT_ID,
           ACC_AUDIT_EVENTS.AUDIT_TIME,
           ACC_AUDIT_EVENTS.USER_NAME,
           ACC_AUDIT_EVENTS.AUDIT_EVENT_TYPE_ID,
           ACC_AUDIT_EVENTS.DESCRIPTION
    FROM dbo.ACC_AUDIT_EVENTS
    WHERE ACC_AUDIT_EVENTS.AUDIT_TIME >= @p_start_date
          AND ACC_AUDIT_EVENTS.AUDIT_TIME < @p_end_date
          AND ACC_AUDIT_EVENTS.AUDIT_EVENT_TYPE_ID = @p_audit_event_type_id;

    RETURN;

END;
GO
