SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE   PROCEDURE [dbo].[PRICING_TURNOVER_FIND_ALL] @cv_1 VARCHAR(2000) OUTPUT
AS
BEGIN

    SET @cv_1 = NULL;

    SELECT ptb.DESCRIPTION,
           ptb.PRICING_TURNOVER_BAND_ID
    FROM dbo.ACC_PRICING_TURNOVER_BANDS AS ptb
    ORDER BY ptb.PRICING_TURNOVER_BAND_ID;

    RETURN;

END;
GO
