SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE   PROCEDURE [dbo].[BULK_PAYMENT_TR_DELETE]  
   @p_bulk_transaction_id numeric
AS 
   
   BEGIN
      DELETE dbo.ACC_BULK_PAYMENT_TRANSACTIONS
      FROM dbo.ACC_BULK_PAYMENT_TRANSACTIONS  AS b
      WHERE b.BULK_TRANSACTION_ID = @p_bulk_transaction_id
   END
GO
