SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE   PROCEDURE [dbo].[CURRENCY_FIND_ALL]
    @cv_1 VARCHAR(2000) OUTPUT
AS
BEGIN
    SET @cv_1 = NULL;

    SELECT c.CURRENCY_CODE_ALPHA3,
           c.DECIMAL_PLACES,
           c.DEFAULT_REMITTANCE_THRESHOLD_MINOR_UNIT         
    FROM dbo.ACC_CURRENCIES AS c
    ORDER BY c.CURRENCY_CODE_ALPHA3;

    RETURN;

END;
GO
