SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE   PROCEDURE [dbo].[DESIGNATOR_FIND_BY_ID]
    @cv_1 VARCHAR(2000) OUTPUT,
    @p_id NUMERIC
AS
BEGIN

    SET @cv_1 = NULL;

    SELECT cd.DESIGNATOR_ID,
           cd.DESCRIPTION,
           cd.CATEGORY_ID,
           cd.TYPE_ID
    FROM dbo.CST_DESIGNATORS AS cd
    WHERE cd.DESIGNATOR_ID = @p_id;

    RETURN;

END;
GO
