SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE   PROCEDURE [dbo].[COUNTRY_MONITOR_FIND_ALL] @cv_1 VARCHAR(2000) OUTPUT
AS
BEGIN

    SET @cv_1 = NULL;

    SELECT cm.MONITOR_ID,
           cm.COUNTRY_ID,
           cm.DESCRIPTION,
           cm.CREATION_DATE
    FROM dbo.ACC_COUNTRY_MONITORS AS cm
        JOIN dbo.ACC_COUNTRIES AS c
            ON (cm.COUNTRY_ID = c.COUNTRY_ID)
    ORDER BY cm.CREATION_DATE DESC,
             c.COUNTRY_NAME;

    RETURN;

END;
GO
