SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE   PROCEDURE [dbo].[ACC_REPORTS_PACKAGE$rpt_merchant_negative_balance] @p_recordset VARCHAR(2000) OUTPUT
AS
BEGIN

    SET @p_recordset = NULL;

    SELECT ag.ACCOUNT_GROUP_NAME AS [Account Group],
           c.CURRENCY_CODE_ALPHA3 AS Currency,
           CAST(SUM(a.BALANCE_MINOR_UNITS) AS FLOAT(53)) / POWER(10, MIN(c.DECIMAL_PLACES)) AS [Consolidated Balance]
    FROM dbo.ACC_ACCOUNT_GROUPS AS ag
        JOIN dbo.ACC_ACCOUNTS AS a
            ON ag.ACCOUNT_GROUP_ID = a.ACCOUNT_GROUP_ID
        JOIN dbo.ACC_CURRENCIES AS c
            ON ag.CURRENCY_CODE_ALPHA3 = c.CURRENCY_CODE_ALPHA3
    WHERE a.ACCOUNT_TYPE_ID IN ( 0, 2, 3 )
    GROUP BY ag.ACCOUNT_GROUP_NAME,
             c.CURRENCY_CODE_ALPHA3
    HAVING SUM(a.BALANCE_MINOR_UNITS) < 0
    ORDER BY ag.ACCOUNT_GROUP_NAME,
             c.CURRENCY_CODE_ALPHA3;

    RETURN;

END;
GO
