SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE   PROCEDURE [dbo].[ACQ_FEE_IC_BY_ID]
    @cv_1 VARCHAR(2000) OUTPUT,
    @p_fee_id NUMERIC
AS
BEGIN

    SET @cv_1 = NULL;

    SELECT ACC_ACQUIRING_FEES_IC.ACQ_FEE_IC_ID,
           ACC_ACQUIRING_FEES_IC.ACCOUNT_GROUP_ID,
           ACC_ACQUIRING_FEES_IC.FEE_DISTINGUISHER,
           ACC_ACQUIRING_FEES_IC.AMOUNT_MINOR_UNITS,
           ACC_ACQUIRING_FEES_IC.PERCENTAGE
    FROM dbo.ACC_ACQUIRING_FEES_IC
    WHERE ACC_ACQUIRING_FEES_IC.ACQ_FEE_IC_ID = @p_fee_id;

    RETURN;

END;
GO
