SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE   PROCEDURE [dbo].[ACC_GLOBAL_SETTING_FIND_BY_ID]
    @cv_1 VARCHAR(2000) OUTPUT,
    @p_setting_name NVARCHAR(50)
AS
BEGIN

    SET @cv_1 = NULL;

    SELECT TBLGLOBALSETTING.SETTINGNAME,
           TBLGLOBALSETTING.SETTINGVALUE
    FROM dbo.TBLGLOBALSETTING
    WHERE TBLGLOBALSETTING.SETTINGNAME = @p_setting_name;

    RETURN;

END;
GO
