SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE   PROCEDURE [dbo].[ACQ_FEE_BLENDED_FROM_TEMPLATES]
    @cv_1 VARCHAR(2000) OUTPUT,
    @p_pricing_turnover_band_id NUMERIC,
    @p_account_group_id NUMERIC
AS
BEGIN

    SET @cv_1 = NULL;

    SELECT ACC_PRICING_TEMPLATES_BLENDED.TEMPLATE_BLENDED_ID AS acq_fee_blended_id,
           @p_account_group_id AS account_group_id,
           ACC_PRICING_TEMPLATES_BLENDED.PERCENTAGE,
           ACC_PRICING_TEMPLATES_BLENDED.AMOUNT_MINOR_UNITS,
           ACC_PRICING_TEMPLATES_BLENDED.CARD_CATEGORY_CODE,
           ACC_PRICING_TEMPLATES_BLENDED.TRANSACTION_CATEGORY_CODE,
           ACC_PRICING_TEMPLATES_BLENDED.REGION_CODE AS region
    FROM dbo.ACC_PRICING_TEMPLATES_BLENDED
    WHERE ACC_PRICING_TEMPLATES_BLENDED.PRICING_TURNOVER_BAND_ID = @p_pricing_turnover_band_id;

    RETURN;

END;
GO
