SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE   PROCEDURE [dbo].[PRELOAD_DESTINATION_EXISTS]
    @cv_1 VARCHAR(2000) OUTPUT,
    @p_currency_code_alpha3 NVARCHAR(2000),
    @p_owner_id NUMERIC
AS
SET NOCOUNT ON;
BEGIN

    SET @cv_1 = NULL;

    SELECT COUNT(*) AS scalarvalue
    FROM dbo.ACC_PRELOAD_DESTINATION
    WHERE ACC_PRELOAD_DESTINATION.CURRENCY_CODE_ALPHA3 = @p_currency_code_alpha3
          AND ACC_PRELOAD_DESTINATION.OWNER_ID = @p_owner_id;

    RETURN;

END;
GO
