SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE   PROCEDURE [dbo].[spCostVisaInterchangeFeeCreate]
    @afs                           NVARCHAR(1),
    @amountCurrency                NCHAR(3),
    @ati                           NVARCHAR(100),
    @authCharac                    NVARCHAR(100),
    @authCode                      NVARCHAR(100),
    @authRespCode                  NCHAR(2),
    @businessApplicationIdentifier NVARCHAR(100),
    @cappedMajorUnit               DECIMAL(18,8),
    @cardholderIdMethod            NCHAR(1),
    @cardCapabilityFlag            NCHAR(1),
    @chipTerminalDeploymentFlag    NCHAR(1),
    @cvvResult                     NVARCHAR(100),
    @dcci                          NVARCHAR(100),
    @effectiveFrom                 DATETIME2,
    @effectiveUntil                DATETIME2,
    @excludingMccs                 NVARCHAR(1000),
    @feeDescriptor                 NVARCHAR(50),
    @feePercentAsMultiplier        DECIMAL(18,8),
    @feeScenario                   NVARCHAR(50),
    @fixedCurrency                 NCHAR(3),
    @fixedFeeMajorUnit             DECIMAL(18,8),
    @fpi                           NVARCHAR(100),
    @issuerCountryRegion           NVARCHAR(50),
    @maximumAmountMajorUnit        DECIMAL(18,2),
    @mccSpecific                   NCHAR(4),
    @merchantCountryRegion         NVARCHAR(50),
    @minimumAmountMajorUnit        DECIMAL(18,2),
    @motoEci                       NVARCHAR(100),
    @pid                           NCHAR(2),
    @posEntryMode                  NCHAR(2),
    @posEnvCode                    NVARCHAR(100),
    @posTerminalCapability         NCHAR(1),
    @productSubtype                NVARCHAR(50),
    @productType                   NVARCHAR(50),
    @reimbAttr                     NCHAR(1),
    @requestedPaymentService       NVARCHAR(100),
    @score                         BIGINT,
    @timelinessDays                BIGINT,
    @feeId                         BIGINT
AS
BEGIN
    INSERT dbo.tlkpCostVisaInterchangeFee
    (
        EffectiveFrom,
        EffectiveUntil,
        MerchantCountryRegion,
        IssuerCountryRegion,
        FeeScenario,
        MinimumAmountMajorUnit,
        MaximumAmountMajorUnit,
        AmountCurrency,
        Afs,
        Pid,
        ProductSubtype,
        ProductType,
        FeeDescriptor,
        FeePercentAsMultiplier,
        FixedFeeMajorUnit,
        CappedMajorUnit,
        FixedCurrency,
        Fpi,
        ReimbAttr,
        CardCapabilityFlag,
        PosTerminalCapability,
        AuthCode,
        PosEntryMode,
        CardholderIdMethod,
        MotoEci,
        MccSpecific,
        ExcludingMccs,
        PosEnvCode,
        Ati,
        AuthRespCode,
        CvvResult,
        TimelinessDays,
        ChipTerminalDeploymentFlag,
        BusinessApplicationIdentifier,
        AuthCharac,
        RequestedPaymentService,
        Dcci
    )
    VALUES
    (
        @effectiveFrom,
        @effectiveUntil,
        @merchantCountryRegion,
        @issuerCountryRegion,
        @feeScenario,
        @minimumAmountMajorUnit,
        @maximumAmountMajorUnit,
        @amountCurrency,
        @afs,
        @pid,
        @productSubtype,
        @productType,
        @feeDescriptor,
        @feePercentAsMultiplier,
        @fixedFeeMajorUnit,
        @cappedMajorUnit,
        @fixedCurrency,
        @fpi,
        @reimbAttr,
        @cardCapabilityFlag,
        @posTerminalCapability,
        @authCode,
        @posEntryMode,
        @cardholderIdMethod,
        @motoEci,
        @mccSpecific,
        @excludingMccs,
        @posEnvCode,
        @ati,
        @authRespCode,
        @cvvResult,
        @timelinessDays,
        @chipTerminalDeploymentFlag,
        @businessApplicationIdentifier,
        @authCharac,
        @requestedPaymentService,
        @dcci
    );
END;
GO
