SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE   PROCEDURE [dbo].[GEN_MES_OUT_QUEUE_FIND_ALL] @cv_1 VARCHAR(2000) OUTPUT
AS
BEGIN

    SET @cv_1 = NULL;

    SELECT ACC_GENERIC_MESSAGES_OUT_QUEUE.MESSAGE_ID,
           ACC_GENERIC_MESSAGES_OUT_QUEUE.MESSAGE_TIMESTAMP,
           ACC_GENERIC_MESSAGES_OUT_QUEUE.MESSAGE_TYPE,
           ACC_GENERIC_MESSAGES_OUT_QUEUE.MESSAGE_REFERENCE,
           ACC_GENERIC_MESSAGES_OUT_QUEUE.MESSAGE_TEXT
    FROM dbo.ACC_GENERIC_MESSAGES_OUT_QUEUE
    ORDER BY ACC_GENERIC_MESSAGES_OUT_QUEUE.MESSAGE_TIMESTAMP;

    RETURN;

END;
GO
