CREATE TABLE [dbo].[ACC_ACQUIRING_FEES]
(
[FEE_ID] [bigint] NOT NULL CONSTRAINT [ACC_ACQUIRING_FEES_DEFAULT] DEFAULT (NEXT VALUE FOR [dbo].[ACQUIRING_FEE_SEQUENCE]),
[ACCOUNT_GROUP_ID] [bigint] NOT NULL,
[EVENT_TYPE_ID] [bigint] NOT NULL,
[PERCENTAGE] [decimal] (18, 4) NOT NULL,
[AMOUNT_MINOR_UNITS] [bigint] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ACC_ACQUIRING_FEES] ADD CONSTRAINT [ACC_ACQUIRING_FEES_PK] PRIMARY KEY CLUSTERED  ([FEE_ID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [ACC_ACQUIRING_FEES_ACCOUNT_GROUP_ID_EVENT_TYPE_ID] ON [dbo].[ACC_ACQUIRING_FEES] ([ACCOUNT_GROUP_ID], [EVENT_TYPE_ID]) ON [INDEX]
GO
ALTER TABLE [dbo].[ACC_ACQUIRING_FEES] WITH NOCHECK ADD CONSTRAINT [ACC_ACQ_FEE_ACCOUNT_GROUP_FK] FOREIGN KEY ([ACCOUNT_GROUP_ID]) REFERENCES [dbo].[ACC_ACCOUNT_GROUPS] ([ACCOUNT_GROUP_ID])
GO
ALTER TABLE [dbo].[ACC_ACQUIRING_FEES] WITH NOCHECK ADD CONSTRAINT [ACC_ACQ_FEE_EVENT_TYPE_FK] FOREIGN KEY ([EVENT_TYPE_ID]) REFERENCES [dbo].[ACC_EVENT_TYPES] ([EVENT_TYPE_ID])
GO
