CREATE TABLE [dbo].[CST_DESIGNATOR_LOOKUP]
(
[LOOKUP_ID] [bigint] NOT NULL,
[TRANSFER_METHOD_ID] [bigint] NOT NULL,
[DIRECTION] [char] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[DESIGNATOR_ID] [bigint] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CST_DESIGNATOR_LOOKUP] ADD CONSTRAINT [CST_DESIGNATOR_LOOKUP_PK] PRIMARY KEY CLUSTERED  ([LOOKUP_ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CST_DESIGNATOR_LOOKUP] WITH NOCHECK ADD CONSTRAINT [CST_DESIGNATOR_LOOKUP_DS_FK] FOREIGN KEY ([DESIGNATOR_ID]) REFERENCES [dbo].[CST_DESIGNATORS] ([DESIGNATOR_ID])
GO
ALTER TABLE [dbo].[CST_DESIGNATOR_LOOKUP] WITH NOCHECK ADD CONSTRAINT [CST_DESIGNATOR_LOOKUP_TM_FK] FOREIGN KEY ([TRANSFER_METHOD_ID]) REFERENCES [dbo].[ACC_TRANSFER_METHODS] ([TRANSFER_METHOD_ID])
GO
