CREATE TABLE [dbo].[ACC_BATCHES]
(
[BATCH_ID] [bigint] NOT NULL,
[ACCOUNT_ID] [bigint] NOT NULL,
[MATURITY_DATE] [datetime2] (0) NOT NULL,
[MATURED_TIME] [datetime2] (6) NULL,
[HOLD] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_ACC_BATCHES_HOLD] DEFAULT ('N'),
[PAYMENT_TRANSACTION_ID] [bigint] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ACC_BATCHES] ADD CONSTRAINT [ACC_BATCHES_PK] PRIMARY KEY CLUSTERED  ([BATCH_ID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [ACC_BATCHES_SETTLEMENT_BATCH] ON [dbo].[ACC_BATCHES] ([ACCOUNT_ID]) INCLUDE ([BATCH_ID], [HOLD], [MATURED_TIME], [MATURITY_DATE], [PAYMENT_TRANSACTION_ID]) ON [INDEX]
GO
CREATE NONCLUSTERED INDEX [ACC_BATCHES_MAT_DATE_TIME] ON [dbo].[ACC_BATCHES] ([MATURED_TIME], [MATURITY_DATE]) WITH (PAD_INDEX=ON) ON [INDEX]
GO
ALTER TABLE [dbo].[ACC_BATCHES] WITH NOCHECK ADD CONSTRAINT [ACC_BATCHES_ACCOUNT_ID_FK] FOREIGN KEY ([ACCOUNT_ID]) REFERENCES [dbo].[ACC_ACCOUNTS] ([ACCOUNT_ID])
GO
