CREATE TABLE [dbo].[CST_DESIGNATOR_COSTS_AUD]
(
[COST_ID] [bigint] NOT NULL,
[REV] [numeric] (38, 0) NOT NULL,
[REVTYPE] [smallint] NULL,
[VALID_FROM] [datetime2] (0) NULL,
[DESIGNATOR_ID] [bigint] NULL,
[CURRENCY_CODE_ALPHA3] [char] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FIXED_AMOUNT_MINOR_UNITS] [numeric] (18, 0) NULL,
[VARIABLE_PCTG] [numeric] (8, 4) NULL,
[VALID_TO] [datetime2] (0) NULL,
[MIN_AMOUNT] [numeric] (18, 0) NULL,
[MAX_AMOUNT] [numeric] (18, 0) NULL,
[MIN_RETURN_AMOUNT] [numeric] (18, 0) NULL,
[MAX_RETURN_AMOUNT] [numeric] (18, 0) NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CST_DESIGNATOR_COSTS_AUD] ADD CONSTRAINT [CST_DESIGNATOR_COSTS_AUD_PK] PRIMARY KEY CLUSTERED  ([COST_ID], [REV]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CST_DESIGNATOR_COSTS_AUD] WITH NOCHECK ADD CONSTRAINT [CST_DESIGNATOR_COSTS_AUD_FK] FOREIGN KEY ([REV]) REFERENCES [dbo].[AUD_REVINFO] ([ID])
GO
