CREATE TABLE [dbo].[ACC_PRICING_TIER_TRANSFER_FEES]
(
[TIER_TRANSFER_FEE_ID] [bigint] NOT NULL CONSTRAINT [ACC_PRICING_TIER_TRANSFER_FEES_DEFAULT] DEFAULT (NEXT VALUE FOR [dbo].[PRICING_TIER_XFER_SEQUENCE]),
[PRICING_TIER_ID] [bigint] NOT NULL,
[TRANSFER_METHOD_ID] [bigint] NOT NULL,
[CURRENCY_CODE_ALPHA3] [char] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[AMOUNT_MINOR_UNITS_OUT] [bigint] NOT NULL,
[AMOUNT_MINOR_UNITS_IN] [bigint] NOT NULL,
[AMOUNT_MINOR_UNITS_OUT_ADD] [bigint] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ACC_PRICING_TIER_TRANSFER_FEES] ADD CONSTRAINT [ACC_PRICING_TRANSFER_FEES_PK] PRIMARY KEY CLUSTERED  ([TIER_TRANSFER_FEE_ID]) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [ACC_TIER_TRANSFER_FEE_IDX] ON [dbo].[ACC_PRICING_TIER_TRANSFER_FEES] ([PRICING_TIER_ID], [TRANSFER_METHOD_ID], [CURRENCY_CODE_ALPHA3]) WITH (PAD_INDEX=ON) ON [INDEX]
GO
ALTER TABLE [dbo].[ACC_PRICING_TIER_TRANSFER_FEES] WITH NOCHECK ADD CONSTRAINT [ACC_TIER_XFER_CURRENCY_FK] FOREIGN KEY ([CURRENCY_CODE_ALPHA3]) REFERENCES [dbo].[ACC_CURRENCIES] ([CURRENCY_CODE_ALPHA3])
GO
ALTER TABLE [dbo].[ACC_PRICING_TIER_TRANSFER_FEES] WITH NOCHECK ADD CONSTRAINT [ACC_TIER_XFER_PRICING_TIER_FK] FOREIGN KEY ([PRICING_TIER_ID]) REFERENCES [dbo].[ACC_PRICING_TIERS] ([PRICING_TIER_ID])
GO
ALTER TABLE [dbo].[ACC_PRICING_TIER_TRANSFER_FEES] WITH NOCHECK ADD CONSTRAINT [ACC_TIER_XFER_XFER_METHOD_FK] FOREIGN KEY ([TRANSFER_METHOD_ID]) REFERENCES [dbo].[ACC_TRANSFER_METHODS] ([TRANSFER_METHOD_ID])
GO
