CREATE TABLE [dbo].[AUD_REVINFO]
(
[ID] [numeric] (38, 0) NOT NULL,
[REVISION_TIMESTAMP] [datetime2] (0) NULL,
[USER_NAME] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AUD_REVINFO] ADD CONSTRAINT [AUD_REVINFO_PK] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
