CREATE TABLE [dbo].[ACC_ACCOUNT_STATEMENTS]
(
[ACCOUNT_STATEMENT_ID] [bigint] NOT NULL,
[STATEMENT_MONTH] [datetime2] (0) NOT NULL,
[TRANSFER_TYPE_ID] [bigint] NULL,
[QUANTITY] [bigint] NOT NULL,
[TOTAL_MINOR_UNITS] [bigint] NOT NULL,
[ACCOUNT_GROUP_ID] [bigint] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ACC_ACCOUNT_STATEMENTS] ADD CONSTRAINT [ACCOUNT_STATEMENT_PK] PRIMARY KEY CLUSTERED  ([ACCOUNT_STATEMENT_ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ACC_ACCOUNT_STATEMENTS] WITH NOCHECK ADD CONSTRAINT [ACCOUNT_STTMNT_ACCOUNT_GRP_FK] FOREIGN KEY ([ACCOUNT_GROUP_ID]) REFERENCES [dbo].[ACC_ACCOUNT_GROUPS] ([ACCOUNT_GROUP_ID])
GO
