CREATE TABLE [dbo].[ACC_SESSIONS_JSF]
(
[SESSION_UUID] [nvarchar] (36) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[SESSION_STATE] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[EXPIRY_TIME] [datetime2] (6) NULL,
[ACCESS_COUNT] [int] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ACC_SESSIONS_JSF] ADD CONSTRAINT [ACC_SESSIONS_JSF_PK] PRIMARY KEY CLUSTERED  ([SESSION_UUID]) ON [PRIMARY]
GO
