CREATE TABLE [dbo].[FX_RATES]
(
[RATE_ID] [bigint] NOT NULL,
[RATE_DATE] [datetime2] (0) NOT NULL,
[FROM_CURRENCY] [char] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[TO_CURRENCY] [char] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[RATE] [numeric] (12, 5) NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[FX_RATES] ADD CONSTRAINT [FX_RATES_PK] PRIMARY KEY CLUSTERED  ([RATE_ID]) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [FX_RATE_KEY] ON [dbo].[FX_RATES] ([RATE_DATE], [FROM_CURRENCY], [TO_CURRENCY]) WITH (PAD_INDEX=ON) ON [INDEX]
GO
CREATE NONCLUSTERED INDEX [IX_FXRATES_DATETOCURRENCY] ON [dbo].[FX_RATES] ([RATE_DATE], [TO_CURRENCY]) INCLUDE ([FROM_CURRENCY], [RATE]) ON [INDEX]
GO
