CREATE TABLE [dbo].[ACC_HSBC_ACCOUNTS]
(
[ACCOUNT_ID] [bigint] NOT NULL,
[CURRENCY_CODE_ALPHA3] [char] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ACCOUNT_NUMBER] [nvarchar] (35) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DESCRIPTION] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[STATEMENT_ENABLED] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_ACC_HSBC_ACCOUNTS_STATEMENT_ENABLED] DEFAULT ('Y')
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ACC_HSBC_ACCOUNTS] ADD CONSTRAINT [ACC_HSBC_ACCT_PK] PRIMARY KEY CLUSTERED  ([ACCOUNT_ID]) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [ACC_HSBC_ACCOUNTS_NUMBER_UI] ON [dbo].[ACC_HSBC_ACCOUNTS] ([ACCOUNT_NUMBER]) WITH (PAD_INDEX=ON) ON [INDEX]
GO
ALTER TABLE [dbo].[ACC_HSBC_ACCOUNTS] WITH NOCHECK ADD CONSTRAINT [ACC_HSBC_ACCT_CURR_FK] FOREIGN KEY ([CURRENCY_CODE_ALPHA3]) REFERENCES [dbo].[ACC_CURRENCIES] ([CURRENCY_CODE_ALPHA3])
GO
