CREATE TABLE [dbo].[ACC_REGIONS]
(
[REGION_CODE] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[NAME] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ACC_REGIONS] ADD CONSTRAINT [ACC_REGION_PK] PRIMARY KEY CLUSTERED  ([REGION_CODE]) ON [PRIMARY]
GO
