CREATE TABLE [dbo].[ACC_PRICING_SALES_DEFAULTS]
(
[PRICE_DEFAULT_ID] [bigint] NOT NULL,
[CURRENCY_CODE_ALPHA3] [char] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[CARD_TYPE_ID] [bigint] NOT NULL,
[SALE_CLASS_ID] [bigint] NOT NULL,
[REGION] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_ACC_PRICING_SALES_DEFAULTS_REGION] DEFAULT ('D'),
[FIXED] [bigint] NOT NULL CONSTRAINT [DF_ACC_PRICING_SALES_DEFAULTS_FIXED] DEFAULT ((0)),
[PERCENTAGE] [numeric] (18, 9) NOT NULL CONSTRAINT [DF_ACC_PRICING_SALES_DEFAULTS_PERCENTAGE] DEFAULT ((0)),
[PRICING_TURNOVER_BAND_ID] [bigint] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ACC_PRICING_SALES_DEFAULTS] ADD CONSTRAINT [ACC_PRICING_SALES_DEFAULTS_PK] PRIMARY KEY CLUSTERED  ([PRICE_DEFAULT_ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ACC_PRICING_SALES_DEFAULTS] WITH NOCHECK ADD CONSTRAINT [ACC_PRICE_SALE_DEF_TURNOVER_FK] FOREIGN KEY ([PRICING_TURNOVER_BAND_ID]) REFERENCES [dbo].[ACC_PRICING_TURNOVER_BANDS] ([PRICING_TURNOVER_BAND_ID])
GO
ALTER TABLE [dbo].[ACC_PRICING_SALES_DEFAULTS] WITH NOCHECK ADD CONSTRAINT [ACC_SALES_DEFAULTS_CARD_FK] FOREIGN KEY ([CARD_TYPE_ID]) REFERENCES [dbo].[ACC_CARD_TYPES] ([CARD_TYPE_ID])
GO
ALTER TABLE [dbo].[ACC_PRICING_SALES_DEFAULTS] WITH NOCHECK ADD CONSTRAINT [ACC_SALES_DEFAULTS_CURRENCY_FK] FOREIGN KEY ([CURRENCY_CODE_ALPHA3]) REFERENCES [dbo].[ACC_CURRENCIES] ([CURRENCY_CODE_ALPHA3])
GO
ALTER TABLE [dbo].[ACC_PRICING_SALES_DEFAULTS] WITH NOCHECK ADD CONSTRAINT [ACC_SALES_DEFAULTS_SALE_FK] FOREIGN KEY ([SALE_CLASS_ID]) REFERENCES [dbo].[ACC_SALE_CLASSES] ([SALE_CLASS_ID])
GO
