CREATE TABLE [dbo].[ACC_PRICING_REGIONS]
(
[PRICING_REGION_CODE] [nvarchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ACC_PRICING_REGIONS] ADD CONSTRAINT [ACC_PRICING_REGION_PK] PRIMARY KEY CLUSTERED  ([PRICING_REGION_CODE]) ON [PRIMARY]
GO
