CREATE TABLE [dbo].[ACC_BULK_PAYMENT_TRANSACTIONS]
(
[BULK_TRANSACTION_ID] [bigint] NOT NULL,
[BATCH_ID] [bigint] NOT NULL,
[COMMENTS] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PAYMENT_CURRENCY] [char] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[PAYMENT_DATE] [datetime2] (0) NOT NULL,
[ACCOUNT_GROUP_ID] [bigint] NOT NULL,
[BANK_NAME] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BANK_ADDRESS1] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BANK_ADDRESS2] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BANK_ADDRESS3] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BANK_COUNTRY] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BENEFICIARY_NAME] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BENEFICIARY_ADDRESS1] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BENEFICIARY_ADDRESS2] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BENEFICIARY_ADDRESS3] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BENEFICIARY_COUNTRY] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BENEFICIARY_REFERENCE] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BANK_ACCOUNTNAME] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BANK_SORTCODE] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BANK_ACCOUNT_NUMBER] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BANK_SWIFT_CODE] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BANK_AND_BRANCH_CODE] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BSB_CODE] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[HKSG_BANK_AND_BRANCH_CODE] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IBAN] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ABA_NUMBER] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GENERAL_ACCOUNT_NUMBER] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AGENT_BANK_SWIFT_CODE] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PAYMENT_TYPE] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[AMOUNT_MINOR_UNITS] [numeric] (18, 0) NOT NULL,
[STATUS] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[PAYER_NAME] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PAYER_ADDRESS1] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PAYER_ADDRESS2] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PAYER_ADDRESS3] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PAYER_COUNTRY] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ROUTING_TRANSIT_NUMBER] [nvarchar] (9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[COVER_ALL_PAYMENT_FEES] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_ACC_BULK_PAYMENT_TRANSACTIONS_COVER_ALL_PAYMENT_FEES] DEFAULT ('N'),
[SA_BANK_BRANCH_CODE] [nvarchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ACC_BULK_PAYMENT_TRANSACTIONS] ADD CONSTRAINT [ACC_BULK_PAYMENT_TRANS_PK] PRIMARY KEY CLUSTERED  ([BULK_TRANSACTION_ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ACC_BULK_PAYMENT_TRANSACTIONS] WITH NOCHECK ADD CONSTRAINT [ACC_BULK_PAY_TRANS_AG_FK] FOREIGN KEY ([ACCOUNT_GROUP_ID]) REFERENCES [dbo].[ACC_ACCOUNT_GROUPS] ([ACCOUNT_GROUP_ID])
GO
ALTER TABLE [dbo].[ACC_BULK_PAYMENT_TRANSACTIONS] WITH NOCHECK ADD CONSTRAINT [ACC_BULK_PAY_TRANS_BATCH_FK] FOREIGN KEY ([BATCH_ID]) REFERENCES [dbo].[ACC_BULK_PAYMENT_BATCHES] ([BATCH_ID])
GO
