CREATE TABLE [dbo].[ACC_SEPA_ENABLED_CODES]
(
[BIC_CODE] [nvarchar] (35) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ACC_SEPA_ENABLED_CODES] ADD CONSTRAINT [PK_ACC_SEPA_ENABLED_CODES] PRIMARY KEY CLUSTERED  ([BIC_CODE]) ON [PRIMARY]
GO
