CREATE TABLE [dbo].[ACC_PROCESSORS]
(
[ACC_PROCESSOR_ID] [bigint] NOT NULL,
[PROCESSOR_NAME] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[CRON_CHANGE_USERNAME] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CRON_CHANGE_TIMESTAMP] [datetime2] (6) NULL,
[CRON_STRING] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CRON_ENABLED] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[LAST_RUN_USERNAME] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LAST_RUN_TIMESTAMP] [datetime2] (6) NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ACC_PROCESSORS] ADD CONSTRAINT [ACC_PROCESSOR_PK] PRIMARY KEY CLUSTERED  ([ACC_PROCESSOR_ID]) ON [PRIMARY]
GO
