CREATE TABLE [dbo].[ACC_BULK_PAYMENT_BATCHES]
(
[BATCH_ID] [bigint] NOT NULL,
[OWNER_ID] [bigint] NOT NULL,
[DESCRIPTION] [nvarchar] (35) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PAYMENT_COUNT] [numeric] (18, 0) NOT NULL,
[IMPORT_DATE] [datetime2] (0) NOT NULL,
[SUBMIT_DATE] [datetime2] (0) NULL,
[STATUS] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[BULK_PAYMENT_SOURCE_ID] [bigint] NULL CONSTRAINT [DF_ACC_BULK_PAYMENT_BATCHES_BULK_PAYMENT_SOURCE_ID] DEFAULT ((0)),
[ACCOUNT_GROUP_ID] [bigint] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ACC_BULK_PAYMENT_BATCHES] ADD CONSTRAINT [ACC_BULK_PAYMENT_BATCHES_PK] PRIMARY KEY CLUSTERED  ([BATCH_ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ACC_BULK_PAYMENT_BATCHES] WITH NOCHECK ADD CONSTRAINT [ACC_BULK_PAY_BATCH_OWNER_FK] FOREIGN KEY ([OWNER_ID]) REFERENCES [dbo].[ACC_OWNERS] ([OWNER_ID])
GO
ALTER TABLE [dbo].[ACC_BULK_PAYMENT_BATCHES] WITH NOCHECK ADD CONSTRAINT [ACC_BULK_PAYMENT_BATCHES_FK] FOREIGN KEY ([BULK_PAYMENT_SOURCE_ID]) REFERENCES [dbo].[ACC_PAYMENT_SOURCES] ([BULK_PAYMENT_SOURCE_ID])
GO
