CREATE TABLE [dbo].[ACC_PRICING_TEMPLATES_BLENDED]
(
[TEMPLATE_BLENDED_ID] [bigint] NOT NULL,
[REGION_CODE] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[AMOUNT_MINOR_UNITS] [bigint] NOT NULL,
[PERCENTAGE] [numeric] (18, 4) NOT NULL,
[PRICING_TURNOVER_BAND_ID] [bigint] NOT NULL,
[TRANSACTION_CATEGORY_CODE] [nvarchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CARD_CATEGORY_CODE] [nvarchar] (7) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ACC_PRICING_TEMPLATES_BLENDED] ADD CONSTRAINT [ACC_TEMLPATE_BLENDED_PK] PRIMARY KEY CLUSTERED  ([TEMPLATE_BLENDED_ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ACC_PRICING_TEMPLATES_BLENDED] WITH NOCHECK ADD CONSTRAINT [ACC_PRICING_TMPL_BL_CARD_FK] FOREIGN KEY ([CARD_CATEGORY_CODE]) REFERENCES [dbo].[ACC_CARD_CATEGORIES] ([CARD_CATEGORY_CODE])
GO
ALTER TABLE [dbo].[ACC_PRICING_TEMPLATES_BLENDED] WITH NOCHECK ADD CONSTRAINT [ACC_PRICING_TMPL_BL_REGION_FK] FOREIGN KEY ([REGION_CODE]) REFERENCES [dbo].[ACC_REGIONS] ([REGION_CODE])
GO
ALTER TABLE [dbo].[ACC_PRICING_TEMPLATES_BLENDED] WITH NOCHECK ADD CONSTRAINT [ACC_PRICING_TMPL_BL_TR_CAT_FK] FOREIGN KEY ([TRANSACTION_CATEGORY_CODE]) REFERENCES [dbo].[ACC_TRANSACTION_CATEGORIES] ([TRANSACTION_CATEGORY_CODE])
GO
ALTER TABLE [dbo].[ACC_PRICING_TEMPLATES_BLENDED] WITH NOCHECK ADD CONSTRAINT [ACC_PRICING_TURNOVER_BAND_FK] FOREIGN KEY ([PRICING_TURNOVER_BAND_ID]) REFERENCES [dbo].[ACC_PRICING_TURNOVER_BANDS] ([PRICING_TURNOVER_BAND_ID])
GO
