CREATE TABLE [dbo].[ACC_CARD_TYPES]
(
[CARD_TYPE_ID] [bigint] NOT NULL,
[NAME] [nvarchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[CARD_CATEGORY_CODE] [nvarchar] (7) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ACC_CARD_TYPES] ADD CONSTRAINT [ACC_CARD_TYPES_PK] PRIMARY KEY CLUSTERED  ([CARD_TYPE_ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ACC_CARD_TYPES] WITH NOCHECK ADD CONSTRAINT [ACC_CARD_TYPES_CAT_PK] FOREIGN KEY ([CARD_CATEGORY_CODE]) REFERENCES [dbo].[ACC_CARD_CATEGORIES] ([CARD_CATEGORY_CODE])
GO
