CREATE TABLE [dbo].[ACC_PRICING_SALES]
(
[SALE_PRICE_ID] [bigint] NOT NULL,
[CARD_TYPE_ID] [bigint] NOT NULL,
[SALE_CLASS_ID] [bigint] NOT NULL,
[REGION] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_ACC_PRICING_SALES_REGION] DEFAULT ('D'),
[FIXED] [bigint] NOT NULL,
[PERCENTAGE] [numeric] (18, 0) NOT NULL,
[ACCOUNT_GROUP_ID] [bigint] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ACC_PRICING_SALES] ADD CONSTRAINT [ACC_PRICING_SALES_PK] PRIMARY KEY CLUSTERED  ([SALE_PRICE_ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ACC_PRICING_SALES] ADD CONSTRAINT [ACC_PRICING_SALES_AG_ID_UI] UNIQUE NONCLUSTERED  ([ACCOUNT_GROUP_ID], [CARD_TYPE_ID], [SALE_CLASS_ID], [REGION]) WITH (PAD_INDEX=ON) ON [INDEX]
GO
CREATE NONCLUSTERED INDEX [ACC_PRICING_SALES_CARD_FI] ON [dbo].[ACC_PRICING_SALES] ([CARD_TYPE_ID]) WITH (PAD_INDEX=ON) ON [INDEX]
GO
CREATE NONCLUSTERED INDEX [ACC_PRICING_SALES_CLASS_FI] ON [dbo].[ACC_PRICING_SALES] ([SALE_CLASS_ID]) WITH (PAD_INDEX=ON) ON [INDEX]
GO
ALTER TABLE [dbo].[ACC_PRICING_SALES] WITH NOCHECK ADD CONSTRAINT [ACC_PRICING_SALES_AG_FK] FOREIGN KEY ([ACCOUNT_GROUP_ID]) REFERENCES [dbo].[ACC_ACCOUNT_GROUPS] ([ACCOUNT_GROUP_ID])
GO
ALTER TABLE [dbo].[ACC_PRICING_SALES] WITH NOCHECK ADD CONSTRAINT [ACC_PRICING_SALES_CARD_FK] FOREIGN KEY ([CARD_TYPE_ID]) REFERENCES [dbo].[ACC_CARD_TYPES] ([CARD_TYPE_ID])
GO
ALTER TABLE [dbo].[ACC_PRICING_SALES] WITH NOCHECK ADD CONSTRAINT [ACC_PRICING_SALES_CLASS_FK] FOREIGN KEY ([SALE_CLASS_ID]) REFERENCES [dbo].[ACC_SALE_CLASSES] ([SALE_CLASS_ID])
GO
