CREATE TABLE [dbo].[ACC_FEES_BY_TURNOVERBAND]
(
[ID] [bigint] NOT NULL,
[PRICING_TURNOVER_BAND_ID] [bigint] NULL,
[CURRENCY_CODE_ALPHA3] [char] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EVENT_TYPE_ID] [bigint] NULL,
[TRANSFER_TYPE_ID] [bigint] NOT NULL,
[PERCENTAGE] [numeric] (20, 2) NULL,
[AMOUNT_MINOR_UNITS] [bigint] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ACC_FEES_BY_TURNOVERBAND] ADD CONSTRAINT [PK_ACC_FEES_BY_TRNOVRBND] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
