CREATE TABLE [dbo].[ACC_OWNER_TYPES]
(
[OWNER_TYPE_ID] [bigint] NOT NULL,
[NAME] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ACC_OWNER_TYPES] ADD CONSTRAINT [PK_ACC_OWNER_TYPES] PRIMARY KEY CLUSTERED  ([OWNER_TYPE_ID]) ON [PRIMARY]
GO
