CREATE TABLE [dbo].[ACC_PRICING_TIER_ALIASES]
(
[PRICING_TIER_ALIAS] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[PRICING_TIER_ID] [bigint] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ACC_PRICING_TIER_ALIASES] ADD CONSTRAINT [ACC_PRICING_TIER_ALIASES_PK] PRIMARY KEY CLUSTERED  ([PRICING_TIER_ALIAS]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ACC_PRICING_TIER_ALIASES] WITH NOCHECK ADD CONSTRAINT [ACC_PRICING_TIER_FK] FOREIGN KEY ([PRICING_TIER_ID]) REFERENCES [dbo].[ACC_PRICING_TIERS] ([PRICING_TIER_ID])
GO
