CREATE TABLE [dbo].[ACC_TRANSFER_TYPES]
(
[TRANSFER_TYPE_ID] [bigint] NOT NULL,
[NAME] [nvarchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[DESCRIPTION] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TRANSFER_TYPE_CLASS_ID] [bigint] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ACC_TRANSFER_TYPES] ADD CONSTRAINT [ACC_TRANSFER_TYPES_PK] PRIMARY KEY CLUSTERED  ([TRANSFER_TYPE_ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ACC_TRANSFER_TYPES] ADD CONSTRAINT [FK_ACC_TRANSFER_TYPES_tlkpTransferTypeClass] FOREIGN KEY ([TRANSFER_TYPE_CLASS_ID]) REFERENCES [dbo].[tlkpTransferTypeClass] ([TransferTypeClassId])
GO
