CREATE TABLE [dbo].[ACC_WITHDRAWAL_REQUESTS]
(
[WITHDRAWAL_ID] [bigint] NOT NULL,
[ACCOUNT_ID] [bigint] NOT NULL,
[ACCOUNT_ID_TO] [bigint] NOT NULL,
[REQUEST_DATE] [datetime2] (0) NOT NULL,
[WITHDRAWAL_DATE] [datetime2] (0) NOT NULL,
[ACTIONED_DATE] [datetime2] (0) NULL,
[WITHDRAWAL_AMOUNT] [bigint] NOT NULL,
[REQUEST_STATE] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_ACC_WITHDRAWAL_REQUESTS_REQUEST_STATE] DEFAULT ('P')
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ACC_WITHDRAWAL_REQUESTS] ADD CONSTRAINT [ACC_WITHDRAWAL_REQUESTS_PK] PRIMARY KEY CLUSTERED  ([WITHDRAWAL_ID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [ACC_WITHD_ACCOUNT_ID_FI] ON [dbo].[ACC_WITHDRAWAL_REQUESTS] ([ACCOUNT_ID]) WITH (PAD_INDEX=ON) ON [INDEX]
GO
CREATE NONCLUSTERED INDEX [ACC_WITHD_ACCOUNT_ID_TO_FI] ON [dbo].[ACC_WITHDRAWAL_REQUESTS] ([ACCOUNT_ID_TO]) WITH (PAD_INDEX=ON) ON [INDEX]
GO
ALTER TABLE [dbo].[ACC_WITHDRAWAL_REQUESTS] WITH NOCHECK ADD CONSTRAINT [ACC_WITHD_ACCOUNT_ID_TO_FK] FOREIGN KEY ([ACCOUNT_ID_TO]) REFERENCES [dbo].[ACC_ACCOUNTS] ([ACCOUNT_ID])
GO
ALTER TABLE [dbo].[ACC_WITHDRAWAL_REQUESTS] WITH NOCHECK ADD CONSTRAINT [ACC_WITHDRAWALS_ACCOUNT_ID_FK] FOREIGN KEY ([ACCOUNT_ID]) REFERENCES [dbo].[ACC_ACCOUNTS] ([ACCOUNT_ID])
GO
