CREATE TABLE [dbo].[ACC_BANK_PAYEES]
(
[PAYEE_ID] [bigint] NOT NULL,
[ACCOUNT_GROUP_ID] [bigint] NOT NULL,
[BANK_NAME] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BANK_ADDRESS1] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BANK_ADDRESS2] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BANK_ADDRESS3] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BANK_SORTCODE] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BANK_ACCOUNTNAME] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BENEFICIARY_ADDRESS1] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BENEFICIARY_ADDRESS2] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BENEFICIARY_ADDRESS3] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BENEFICIARY_REFERENCE] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BANK_ACCOUNT_NUMBER] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BANK_SWIFT_CODE] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BANK_AND_BRANCH_CODE] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BSB_CODE] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[HKSG_BANK_AND_BRANCH_CODE] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IBAN] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ABA_NUMBER] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GENERAL_ACCOUNT_NUMBER] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BENEFICIARY_NAME] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AGENT_BANK_SWIFT_CODE] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BENEFICIARY_COUNTRY] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BANK_COUNTRY] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ROUTING_TRANSIT_NUMBER] [nvarchar] (9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SA_BANK_BRANCH_CODE] [nvarchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ACC_BANK_PAYEES] ADD CONSTRAINT [ACC_PAYEE_DETAILS_PK] PRIMARY KEY CLUSTERED  ([PAYEE_ID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [ACC_BANK_PAYEES_ACCOUNT_GRP_FI] ON [dbo].[ACC_BANK_PAYEES] ([ACCOUNT_GROUP_ID]) WITH (PAD_INDEX=ON) ON [INDEX]
GO
ALTER TABLE [dbo].[ACC_BANK_PAYEES] WITH NOCHECK ADD CONSTRAINT [ACC_BANK_PAYEES_ACCOUNT_GRP_FK] FOREIGN KEY ([ACCOUNT_GROUP_ID]) REFERENCES [dbo].[ACC_ACCOUNT_GROUPS] ([ACCOUNT_GROUP_ID])
GO
