CREATE TABLE [dbo].[ACC_AUDIT_EVENT_TYPES]
(
[AUDIT_EVENT_TYPE_ID] [bigint] NOT NULL,
[NAME] [nvarchar] (32) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ACC_AUDIT_EVENT_TYPES] ADD CONSTRAINT [ACC_AUDIT_EVENT_TYPES_PK] PRIMARY KEY CLUSTERED  ([AUDIT_EVENT_TYPE_ID]) ON [PRIMARY]
GO
