CREATE TABLE [dbo].[ACC_REMIT_DAYS]
(
[REMIT_DAY_ID] [bigint] NOT NULL,
[REMIT_DAY] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ACCOUNT_GROUP_ID] [bigint] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ACC_REMIT_DAYS] ADD CONSTRAINT [ACC_REMIT_ST_ORDER_DAYS_PK] PRIMARY KEY CLUSTERED  ([REMIT_DAY_ID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [ACC_REMIT_DAYS_ACC_GR_IN] ON [dbo].[ACC_REMIT_DAYS] ([ACCOUNT_GROUP_ID]) WITH (PAD_INDEX=ON) ON [INDEX]
GO
ALTER TABLE [dbo].[ACC_REMIT_DAYS] WITH NOCHECK ADD CONSTRAINT [REMIT_DAYS_ACC_GR_ID_FK] FOREIGN KEY ([ACCOUNT_GROUP_ID]) REFERENCES [dbo].[ACC_ACCOUNT_GROUPS] ([ACCOUNT_GROUP_ID])
GO
