CREATE TABLE [dbo].[ACC_TRANSACTION_COSTS]
(
[TRANSACTION_COST_ID] [bigint] NOT NULL,
[TRANSACTION_ID] [bigint] NOT NULL,
[TYPE_ID] [bigint] NOT NULL,
[DESIGNATOR_ID] [bigint] NOT NULL,
[FIXED_CURRENCY_CODE_ALPHA3] [char] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FIXED_AMOUNT_MINOR_UNITS] [numeric] (18, 6) NULL,
[VARIABLE_CURRENCY_CODE_ALPHA3] [char] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[VARIABLE_AMOUNT_MINOR_UNITS] [numeric] (24, 6) NULL,
[FX_RATE_APPLIED_PRICING] [numeric] (12, 6) NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ACC_TRANSACTION_COSTS] ADD CONSTRAINT [ACC_TRANSACTION_COSTS_PK] PRIMARY KEY CLUSTERED  ([TRANSACTION_COST_ID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [ACC_TRANSACTION_COSTS_UI] ON [dbo].[ACC_TRANSACTION_COSTS] ([TRANSACTION_ID], [DESIGNATOR_ID]) WITH (PAD_INDEX=ON) ON [INDEX]
GO
ALTER TABLE [dbo].[ACC_TRANSACTION_COSTS] WITH NOCHECK ADD CONSTRAINT [ACC_TRANSACTION_COSTS_CURR_FK] FOREIGN KEY ([FIXED_CURRENCY_CODE_ALPHA3]) REFERENCES [dbo].[ACC_CURRENCIES] ([CURRENCY_CODE_ALPHA3])
GO
ALTER TABLE [dbo].[ACC_TRANSACTION_COSTS] WITH NOCHECK ADD CONSTRAINT [ACC_TRANSACTION_COSTS_TP_FK] FOREIGN KEY ([TYPE_ID]) REFERENCES [dbo].[CST_DESIGNATOR_TYPES] ([TYPE_ID])
GO
