CREATE TABLE [dbo].[ACC_COMMISSION_PLANS]
(
[PLAN_ID] [bigint] NOT NULL,
[PLAN_NAME] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[IS_DEFAULT] [smallint] NULL,
[CRM_ID] [nvarchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ACC_COMMISSION_PLANS] ADD CONSTRAINT [ACC_COMMISSION_PLANS_PK] PRIMARY KEY CLUSTERED  ([PLAN_ID]) ON [PRIMARY]
GO
