CREATE TABLE [dbo].[ACC_FEE_DISTINGUISHERS]
(
[FEE_DISTINGUISHER] [nvarchar] (48) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ACC_FEE_DISTINGUISHERS] ADD CONSTRAINT [ACC_FEE_DISTINGUISHER_PK] PRIMARY KEY CLUSTERED  ([FEE_DISTINGUISHER]) ON [PRIMARY]
GO
