CREATE TABLE [dbo].[ACC_AUDIT_EVENTS]
(
[AUDIT_EVENT_ID] [bigint] NOT NULL,
[AUDIT_TIME] [datetime2] (6) NOT NULL,
[USER_NAME] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[AUDIT_EVENT_TYPE_ID] [bigint] NOT NULL,
[DESCRIPTION] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ACC_AUDIT_EVENTS] ADD CONSTRAINT [ACC_AUDIT_EVENTS_PK] PRIMARY KEY CLUSTERED  ([AUDIT_EVENT_ID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [ACC_AUD_EVENTS_TYPE_ID_FI] ON [dbo].[ACC_AUDIT_EVENTS] ([AUDIT_EVENT_TYPE_ID]) WITH (PAD_INDEX=ON) ON [INDEX]
GO
ALTER TABLE [dbo].[ACC_AUDIT_EVENTS] WITH NOCHECK ADD CONSTRAINT [ACC_AUDIT_EVENTS_TYPE_ID_FK] FOREIGN KEY ([AUDIT_EVENT_TYPE_ID]) REFERENCES [dbo].[ACC_AUDIT_EVENT_TYPES] ([AUDIT_EVENT_TYPE_ID])
GO
