CREATE TABLE [dbo].[ACC_PRICING_POLICY]
(
[PRICING_POLICY_ID] [bigint] NOT NULL,
[NAME] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ACC_PRICING_POLICY] ADD CONSTRAINT [ACC_PRICING_POLICY_PK] PRIMARY KEY CLUSTERED  ([PRICING_POLICY_ID]) ON [PRIMARY]
GO
