CREATE TABLE [dbo].[ACC_CT_PRICING_TMPLS_IC]
(
[PRICING_TURNOVER_BAND_ID] [bigint] NOT NULL,
[PERCENTAGE] [decimal] (18, 2) NOT NULL,
[AMOUNT_MINOR_UNITS] [bigint] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ACC_CT_PRICING_TMPLS_IC] ADD CONSTRAINT [ACC_CT_PRICING_TMPLS_IC_PK] PRIMARY KEY CLUSTERED  ([PRICING_TURNOVER_BAND_ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ACC_CT_PRICING_TMPLS_IC] WITH NOCHECK ADD CONSTRAINT [ACC_CT_PR_TMPLS_IC_TUR_BAND_FK] FOREIGN KEY ([PRICING_TURNOVER_BAND_ID]) REFERENCES [dbo].[ACC_PRICING_TURNOVER_BANDS] ([PRICING_TURNOVER_BAND_ID])
GO
