CREATE TABLE [dbo].[CST_DESIGNATORS]
(
[DESIGNATOR_ID] [bigint] NOT NULL,
[DESCRIPTION] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[CATEGORY_ID] [bigint] NOT NULL,
[TYPE_ID] [bigint] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CST_DESIGNATORS] ADD CONSTRAINT [CST_DESIGNATORS_PK] PRIMARY KEY CLUSTERED  ([DESIGNATOR_ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CST_DESIGNATORS] WITH NOCHECK ADD CONSTRAINT [CST_DESIGNATORS_CAT_FK] FOREIGN KEY ([CATEGORY_ID]) REFERENCES [dbo].[CST_DESIGNATOR_CATEGORIES] ([CATEGORY_ID])
GO
