CREATE TABLE [dbo].[ACC_PRICING_TEMPLATES]
(
[TEMPLATE_ID] [bigint] NOT NULL,
[PRICING_TURNOVER_BAND_ID] [bigint] NOT NULL,
[EVENT_TYPE_ID] [bigint] NOT NULL,
[PERCENTAGE] [decimal] (18, 4) NOT NULL,
[AMOUNT_MINOR_UNITS] [bigint] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ACC_PRICING_TEMPLATES] ADD CONSTRAINT [ACC_TURNOVER_BAND_FEES_PK] PRIMARY KEY CLUSTERED  ([TEMPLATE_ID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [ACC_TURNOVER_BAND_FEE_BAND_IDX] ON [dbo].[ACC_PRICING_TEMPLATES] ([PRICING_TURNOVER_BAND_ID]) WITH (PAD_INDEX=ON) ON [INDEX]
GO
ALTER TABLE [dbo].[ACC_PRICING_TEMPLATES] WITH NOCHECK ADD CONSTRAINT [ACC_BAND_FEE_BAND_FK] FOREIGN KEY ([PRICING_TURNOVER_BAND_ID]) REFERENCES [dbo].[ACC_PRICING_TURNOVER_BANDS] ([PRICING_TURNOVER_BAND_ID])
GO
ALTER TABLE [dbo].[ACC_PRICING_TEMPLATES] WITH NOCHECK ADD CONSTRAINT [ACC_BAND_FEE_EVENT_TYPE_FK] FOREIGN KEY ([EVENT_TYPE_ID]) REFERENCES [dbo].[ACC_EVENT_TYPES] ([EVENT_TYPE_ID])
GO
