CREATE TABLE [dbo].[ACC_MONTHLY_FEES]
(
[MONTHLY_FEE_ID] [bigint] NOT NULL,
[OWNER_ID] [bigint] NOT NULL,
[CURRENCY_CODE_ALPHA3] [char] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[AMOUNT_MINOR_UNITS] [bigint] NOT NULL,
[FEE_TYPE_ID] [numeric] (18, 0) NULL CONSTRAINT [DF_ACC_MONTHLY_FEES_FEE_TYPE_ID] DEFAULT ((1))
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ACC_MONTHLY_FEES] ADD CONSTRAINT [ACC_MONTHLY_FEES_PK] PRIMARY KEY CLUSTERED  ([MONTHLY_FEE_ID]) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [ACC_MONTHLY_FEE_IDX] ON [dbo].[ACC_MONTHLY_FEES] ([OWNER_ID], [CURRENCY_CODE_ALPHA3], [FEE_TYPE_ID]) WITH (PAD_INDEX=ON) ON [INDEX]
GO
ALTER TABLE [dbo].[ACC_MONTHLY_FEES] WITH NOCHECK ADD CONSTRAINT [ACC_MONTHLY_FEE_CURRENCY_FK] FOREIGN KEY ([CURRENCY_CODE_ALPHA3]) REFERENCES [dbo].[ACC_CURRENCIES] ([CURRENCY_CODE_ALPHA3])
GO
ALTER TABLE [dbo].[ACC_MONTHLY_FEES] WITH NOCHECK ADD CONSTRAINT [ACC_MONTHLY_FEE_OWNER_FK] FOREIGN KEY ([OWNER_ID]) REFERENCES [dbo].[ACC_OWNERS] ([OWNER_ID])
GO
