CREATE TABLE [dbo].[ACC_CT_FEES_IC]
(
[ACCOUNT_GROUP_ID] [bigint] NOT NULL,
[PERCENTAGE] [decimal] (18, 2) NOT NULL,
[AMOUNT_MINOR_UNITS] [bigint] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ACC_CT_FEES_IC] ADD CONSTRAINT [ACC_CT_FEES_IC_PK] PRIMARY KEY CLUSTERED  ([ACCOUNT_GROUP_ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ACC_CT_FEES_IC] WITH NOCHECK ADD CONSTRAINT [ACC_CT_FEES_IC_TUR_BAND_FK] FOREIGN KEY ([ACCOUNT_GROUP_ID]) REFERENCES [dbo].[ACC_ACCOUNT_GROUPS] ([ACCOUNT_GROUP_ID])
GO
