CREATE TABLE [dbo].[ACC_SALE_CLASSES]
(
[SALE_CLASS_ID] [bigint] NOT NULL,
[NAME] [nvarchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[TRANSACTION_CATEGORY_CODE] [nvarchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ACC_SALE_CLASSES] ADD CONSTRAINT [ACC_SALE_CLASSES_PK] PRIMARY KEY CLUSTERED  ([SALE_CLASS_ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ACC_SALE_CLASSES] WITH NOCHECK ADD CONSTRAINT [ACC_SALE_CLASSES_TR_PK] FOREIGN KEY ([TRANSACTION_CATEGORY_CODE]) REFERENCES [dbo].[ACC_TRANSACTION_CATEGORIES] ([TRANSACTION_CATEGORY_CODE])
GO
