CREATE TABLE [dbo].[ACC_PRICING_TIERS]
(
[PRICING_TIER_ID] [bigint] NOT NULL,
[DESCRIPTION] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[FEE_TYPE_ID] [numeric] (18, 0) NULL CONSTRAINT [DF_ACC_PRICING_TIERS_FEE_TYPE_ID] DEFAULT ((1)),
[PCI_STATUS_ID] [numeric] (18, 0) NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ACC_PRICING_TIERS] ADD CONSTRAINT [ACC_PRICING_TIERS_PK] PRIMARY KEY CLUSTERED  ([PRICING_TIER_ID]) ON [PRIMARY]
GO
