CREATE TABLE [dbo].[ACC_POSTING_RULES]
(
[EVENT_TYPE_ID] [bigint] NOT NULL,
[FROM_ACCOUNT_TYPE_ID] [bigint] NOT NULL,
[TO_ACCOUNT_TYPE_ID] [bigint] NOT NULL,
[TRANSFER_TYPE_ID] [bigint] NOT NULL,
[ACCOUNT_GROUP_TYPE] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[FROM_ACCOUNT_ARREARS_TYPE_ID] [bigint] NOT NULL,
[TO_ACCOUNT_ARREARS_TYPE_ID] [bigint] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ACC_POSTING_RULES] ADD CONSTRAINT [PK_ACC_POST_RULES] PRIMARY KEY CLUSTERED  ([EVENT_TYPE_ID], [ACCOUNT_GROUP_TYPE], [FROM_ACCOUNT_TYPE_ID], [TO_ACCOUNT_TYPE_ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ACC_POSTING_RULES] WITH NOCHECK ADD CONSTRAINT [ACC_POST_RULE_EVENT_TYPE_FK] FOREIGN KEY ([EVENT_TYPE_ID]) REFERENCES [dbo].[ACC_EVENT_TYPES] ([EVENT_TYPE_ID])
GO
ALTER TABLE [dbo].[ACC_POSTING_RULES] WITH NOCHECK ADD CONSTRAINT [ACC_POST_RULE_FROM_ACCOUNT_FK] FOREIGN KEY ([FROM_ACCOUNT_TYPE_ID]) REFERENCES [dbo].[ACC_ACCOUNT_TYPES] ([ACCOUNT_TYPE_ID])
GO
ALTER TABLE [dbo].[ACC_POSTING_RULES] WITH NOCHECK ADD CONSTRAINT [ACC_POST_RULE_TO_ACCOUNT_FK] FOREIGN KEY ([TO_ACCOUNT_TYPE_ID]) REFERENCES [dbo].[ACC_ACCOUNT_TYPES] ([ACCOUNT_TYPE_ID])
GO
ALTER TABLE [dbo].[ACC_POSTING_RULES] WITH NOCHECK ADD CONSTRAINT [ACC_POST_RULE_TRANSFER_TYPE_FK] FOREIGN KEY ([TRANSFER_TYPE_ID]) REFERENCES [dbo].[ACC_TRANSFER_TYPES] ([TRANSFER_TYPE_ID])
GO
ALTER TABLE [dbo].[ACC_POSTING_RULES] ADD CONSTRAINT [FK_FROM_ACCOUNT_ACC_POSTING_RULES_tlkpArrearsType] FOREIGN KEY ([FROM_ACCOUNT_ARREARS_TYPE_ID]) REFERENCES [dbo].[tlkpArrearsType] ([ArrearsTypeId])
GO
ALTER TABLE [dbo].[ACC_POSTING_RULES] ADD CONSTRAINT [FK_TO_ACCOUNT_ACC_POSTING_RULES_tlkpArrearsType] FOREIGN KEY ([TO_ACCOUNT_ARREARS_TYPE_ID]) REFERENCES [dbo].[tlkpArrearsType] ([ArrearsTypeId])
GO
