CREATE TABLE [dbo].[ACC_PAYER_REMAINING_UNITS]
(
[TRANSFER_METHOD_ID] [bigint] NOT NULL,
[REMAINING_UNITS] [bigint] NULL,
[ACCOUNT_GROUP_ID] [bigint] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ACC_PAYER_REMAINING_UNITS] ADD CONSTRAINT [ACC_PAYER_REMAINING_UNITS_PK] PRIMARY KEY CLUSTERED  ([ACCOUNT_GROUP_ID], [TRANSFER_METHOD_ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ACC_PAYER_REMAINING_UNITS] WITH NOCHECK ADD CONSTRAINT [ACC_PAYER_REMAINING_AG_FK] FOREIGN KEY ([ACCOUNT_GROUP_ID]) REFERENCES [dbo].[ACC_ACCOUNT_GROUPS] ([ACCOUNT_GROUP_ID])
GO
ALTER TABLE [dbo].[ACC_PAYER_REMAINING_UNITS] WITH NOCHECK ADD CONSTRAINT [ACC_PAYER_REMAINING_METHOD_FK] FOREIGN KEY ([TRANSFER_METHOD_ID]) REFERENCES [dbo].[ACC_TRANSFER_METHODS] ([TRANSFER_METHOD_ID])
GO
