CREATE TABLE [dbo].[CST_DESIGNATOR_CATEGORIES]
(
[CATEGORY_ID] [bigint] NOT NULL,
[DESCRIPTION] [nvarchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CST_DESIGNATOR_CATEGORIES] ADD CONSTRAINT [CST_DESIGNATOR_CATEGORIES_PK] PRIMARY KEY CLUSTERED  ([CATEGORY_ID]) ON [PRIMARY]
GO
