CREATE TABLE [dbo].[ACC_TRANSFER_METHODS]
(
[TRANSFER_METHOD_ID] [bigint] NOT NULL,
[DESCRIPTION] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[PAYMENT_TYPE_MNEMONIC] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_ACC_TRANSFER_METHODS_PAYMENT_TYPE_MNEMONIC] DEFAULT ('??')
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ACC_TRANSFER_METHODS] ADD CONSTRAINT [ACC_TRANSFER_METHODS_PK] PRIMARY KEY CLUSTERED  ([TRANSFER_METHOD_ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ACC_TRANSFER_METHODS] ADD CONSTRAINT [ACC_TRANSFER_METHODS_MNEM_UI] UNIQUE NONCLUSTERED  ([PAYMENT_TYPE_MNEMONIC]) ON [INDEX]
GO
