CREATE TABLE [dbo].[ACC_PRICING_TIER_MONTHLY_FEES]
(
[TIER_MONTHLY_FEE_ID] [bigint] NOT NULL CONSTRAINT [ACC_PRICING_TIER_MONTHLY_FEES_DEFAULT] DEFAULT (NEXT VALUE FOR [dbo].[PRICING_TIER_MONTH_SEQUENCE]),
[PRICING_TIER_ID] [bigint] NOT NULL,
[CURRENCY_CODE_ALPHA3] [char] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[AMOUNT_MINOR_UNITS] [bigint] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ACC_PRICING_TIER_MONTHLY_FEES] ADD CONSTRAINT [ACC_PRICING_MONTHLY_FEES_PK] PRIMARY KEY CLUSTERED  ([TIER_MONTHLY_FEE_ID]) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [ACC_TIER_MONTHLY_FEE_IDX] ON [dbo].[ACC_PRICING_TIER_MONTHLY_FEES] ([PRICING_TIER_ID], [CURRENCY_CODE_ALPHA3]) WITH (PAD_INDEX=ON) ON [INDEX]
GO
ALTER TABLE [dbo].[ACC_PRICING_TIER_MONTHLY_FEES] WITH NOCHECK ADD CONSTRAINT [ACC_TIER_MONTH_CURRENCY_FK] FOREIGN KEY ([CURRENCY_CODE_ALPHA3]) REFERENCES [dbo].[ACC_CURRENCIES] ([CURRENCY_CODE_ALPHA3])
GO
ALTER TABLE [dbo].[ACC_PRICING_TIER_MONTHLY_FEES] WITH NOCHECK ADD CONSTRAINT [ACC_TIER_MONTH_PRICING_TIER_FK] FOREIGN KEY ([PRICING_TIER_ID]) REFERENCES [dbo].[ACC_PRICING_TIERS] ([PRICING_TIER_ID])
GO
