CREATE TABLE [dbo].[CST_DESIGNATOR_ACQ_LOOKUP_AUD]
(
[LOOKUP_ID] [bigint] NOT NULL,
[REV] [numeric] (38, 0) NOT NULL,
[REVTYPE] [smallint] NULL,
[FEE_PROGRAM] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RATE_TIER] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[INTERCHANGE_DESCRIPTION] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DESIGNATOR_ID] [bigint] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CST_DESIGNATOR_ACQ_LOOKUP_AUD] ADD CONSTRAINT [CST_DESIG_ACQ_LOOKUP_AUD_PK] PRIMARY KEY CLUSTERED  ([LOOKUP_ID], [REV]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CST_DESIGNATOR_ACQ_LOOKUP_AUD] WITH NOCHECK ADD CONSTRAINT [CST_DESIG_ACQ_LOOKUP_AUD_FK] FOREIGN KEY ([REV]) REFERENCES [dbo].[AUD_REVINFO] ([ID])
GO
