CREATE TABLE [dbo].[ACC_BANK_PAYMENT_REQUESTS]
(
[REQUEST_ID] [bigint] NOT NULL,
[REQUEST_DATE] [datetime2] (6) NOT NULL,
[AMOUNT_MINOR_UNITS] [bigint] NOT NULL,
[ACCOUNT_GROUP_ID] [bigint] NOT NULL,
[PAYMENT_TYPE] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[REQUEST_STATE] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[BANK_NAME] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BANK_ADDRESS1] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BANK_ADDRESS2] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BANK_ADDRESS3] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BANK_SORTCODE] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BENEFICIARY_NAME] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BENEFICIARY_ADDRESS1] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BENEFICIARY_ADDRESS2] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BENEFICIARY_ADDRESS3] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BENEFICIARY_REFERENCE] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BANK_ACCOUNT_NUMBER] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BANK_SWIFT_CODE] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BANK_AND_BRANCH_CODE] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BSB_CODE] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[HKSG_BANK_AND_BRANCH_CODE] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IBAN] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ABA_NUMBER] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GENERAL_ACCOUNT_NUMBER] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AGENT_BANK_SWIFT_CODE] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BANK_COUNTRY] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BENEFICIARY_COUNTRY] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BANK_ACCOUNTNAME] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SCHEDULED_DATE] [datetime2] (0) NULL,
[PAYER_NAME] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PAYER_ADDRESS1] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PAYER_ADDRESS2] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PAYER_ADDRESS3] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PAYER_COUNTRY] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ROUTING_TRANSIT_NUMBER] [nvarchar] (9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SA_BANK_BRANCH_CODE] [nvarchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ACC_BANK_PAYMENT_REQUESTS] ADD CONSTRAINT [ACC_BANK_PAYREQ_PK] PRIMARY KEY CLUSTERED  ([REQUEST_ID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [ACC_BANK_PAYREQ_ACCGRP_FI] ON [dbo].[ACC_BANK_PAYMENT_REQUESTS] ([ACCOUNT_GROUP_ID]) WITH (PAD_INDEX=ON) ON [INDEX]
GO
CREATE NONCLUSTERED INDEX [ACC_BANK_PAY_REQ_DATE_STATE_IN] ON [dbo].[ACC_BANK_PAYMENT_REQUESTS] ([REQUEST_DATE], [REQUEST_STATE]) WITH (PAD_INDEX=ON) ON [INDEX]
GO
ALTER TABLE [dbo].[ACC_BANK_PAYMENT_REQUESTS] WITH NOCHECK ADD CONSTRAINT [ACC_BANK_PAYREQ_ACCGRP_FK] FOREIGN KEY ([ACCOUNT_GROUP_ID]) REFERENCES [dbo].[ACC_ACCOUNT_GROUPS] ([ACCOUNT_GROUP_ID]) ON DELETE CASCADE
GO
ALTER TABLE [dbo].[ACC_BANK_PAYMENT_REQUESTS] ADD CONSTRAINT [ACC_TRANSFER_METH_MNEM_FK] FOREIGN KEY ([PAYMENT_TYPE]) REFERENCES [dbo].[ACC_TRANSFER_METHODS] ([PAYMENT_TYPE_MNEMONIC]) ON DELETE CASCADE
GO
