CREATE TABLE [dbo].[ACC_MERCHANT_TYPES]
(
[MERCHANT_TYPE_ID] [bigint] NOT NULL,
[MERCHANT_TYPE_NAME] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ACC_MERCHANT_TYPES] ADD CONSTRAINT [ACC_MERCHANT_TYPES_PK] PRIMARY KEY CLUSTERED  ([MERCHANT_TYPE_ID]) ON [PRIMARY]
GO
