CREATE TABLE [dbo].[ACC_PARTNERS]
(
[CRM_ID] [nvarchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[PARTNER_NAME] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[PARTNER_OVERRIDE] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PARTNER_ID] [bigint] NOT NULL,
[WEBSITE_URL] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PARTNER_TYPE_ID] [bigint] NULL,
[VISA_ISO_CODE] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MASTER_CARD_ISO_CODE] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ACC_PARTNERS] ADD CONSTRAINT [ACC_PARTNERS_ID_PK] PRIMARY KEY CLUSTERED  ([PARTNER_ID]) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [ACC_PARTNERS_CRM_ID_IDX] ON [dbo].[ACC_PARTNERS] ([CRM_ID]) WITH (PAD_INDEX=ON) ON [INDEX]
GO
