CREATE TABLE [dbo].[MVIEW_REMITTANCE_DETAILS]
(
[OWNER_ID] [bigint] NOT NULL,
[OWNER_NAME] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CURRENCY] [char] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ON_HOLD] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ON_HOLD_REASON] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ACCOUNT_GROUP_ID] [bigint] NOT NULL,
[ACCOUNT_GROUP_NAME] [nvarchar] (256) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TOTAL_REMITTANCE] [bigint] NOT NULL,
[TOTAL_PENDING] [bigint] NOT NULL,
[TRADING_ACCOUNT_BALANCE] [bigint] NOT NULL,
[SECURITY_ACCOUNT_BALANCE] [bigint] NOT NULL,
[RESERVE_ACCOUNT_BALANCE] [bigint] NOT NULL,
[ACCOUNT_NUMBER] [int] NULL,
[BUSINESS_ID] [nvarchar] (23) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
