CREATE TABLE [dbo].[ACC_PRICING_TEMPLATES_IC]
(
[TEMPLATE_IC_ID] [bigint] NOT NULL,
[PRICING_TURNOVER_BAND_ID] [bigint] NOT NULL,
[PERCENTAGE] [decimal] (18, 2) NOT NULL,
[AMOUNT_MINOR_UNITS] [bigint] NOT NULL,
[FEE_DISTINGUISHER] [nvarchar] (48) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ACC_PRICING_TEMPLATES_IC] ADD CONSTRAINT [ACC_TEMPLATE_IC_PK] PRIMARY KEY CLUSTERED  ([TEMPLATE_IC_ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ACC_PRICING_TEMPLATES_IC] WITH NOCHECK ADD CONSTRAINT [ACC_TMPL_IC_TURNOVER_BAND_FK] FOREIGN KEY ([PRICING_TURNOVER_BAND_ID]) REFERENCES [dbo].[ACC_PRICING_TURNOVER_BANDS] ([PRICING_TURNOVER_BAND_ID])
GO
