CREATE TABLE [dbo].[ACC_AGGREGATED_TRANSACTIONS]
(
[DECLINE_COUNT] [bigint] NOT NULL,
[AUTHORISATION_COUNT] [bigint] NULL,
[ACCOUNT_GROUP_ID] [bigint] NOT NULL,
[EVENT_DATE] [datetime2] (0) NOT NULL,
[SOURCE_REF] [nvarchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_ACC_AGGREGATED_TRANSACTIONS_SOURCE_REF] DEFAULT ('Unknown')
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ACC_AGGREGATED_TRANSACTIONS] ADD CONSTRAINT [ACC_AGGREG_TXNS_PK] PRIMARY KEY CLUSTERED  ([ACCOUNT_GROUP_ID], [EVENT_DATE], [SOURCE_REF]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ACC_AGGREGATED_TRANSACTIONS] WITH NOCHECK ADD CONSTRAINT [ACC_AGG_TXNS_ACCOUNT_GROUP_FK] FOREIGN KEY ([ACCOUNT_GROUP_ID]) REFERENCES [dbo].[ACC_ACCOUNT_GROUPS] ([ACCOUNT_GROUP_ID])
GO
