CREATE TABLE [dbo].[ACC_TRANSACTION_MARGINS]
(
[TRANSACTION_MARGIN_ID] [bigint] NOT NULL,
[TRANSACTION_ID] [bigint] NOT NULL,
[TYPE_ID] [bigint] NOT NULL,
[FIXED_CURRENCY_CODE_ALPHA3] [char] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FIXED_AMOUNT_MINOR_UNITS] [numeric] (18, 6) NULL,
[VAR_CURRENCY_CODE_ALPHA3] [char] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[VAR_AMOUNT_MINOR_UNITS] [numeric] (18, 6) NULL,
[FX_RATE_APPLIED_PRICING] [numeric] (12, 6) NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ACC_TRANSACTION_MARGINS] ADD CONSTRAINT [ACC_TRANS_MARGINS_PK] PRIMARY KEY CLUSTERED  ([TRANSACTION_MARGIN_ID]) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [ACC_TRANS_MARGINS_UI] ON [dbo].[ACC_TRANSACTION_MARGINS] ([TRANSACTION_ID], [TYPE_ID]) WITH (PAD_INDEX=ON) ON [INDEX]
GO
ALTER TABLE [dbo].[ACC_TRANSACTION_MARGINS] WITH NOCHECK ADD CONSTRAINT [ACC_TRANS_MARGINS_FIX_CURR_FK] FOREIGN KEY ([FIXED_CURRENCY_CODE_ALPHA3]) REFERENCES [dbo].[ACC_CURRENCIES] ([CURRENCY_CODE_ALPHA3])
GO
ALTER TABLE [dbo].[ACC_TRANSACTION_MARGINS] WITH NOCHECK ADD CONSTRAINT [ACC_TRANS_MARGINS_TYPE_ID_FK] FOREIGN KEY ([TYPE_ID]) REFERENCES [dbo].[ACC_TRANSACTION_MARGIN_TYPES] ([TYPE_ID])
GO
ALTER TABLE [dbo].[ACC_TRANSACTION_MARGINS] WITH NOCHECK ADD CONSTRAINT [ACC_TRANS_MARGINS_VAR_CURR_FK] FOREIGN KEY ([VAR_CURRENCY_CODE_ALPHA3]) REFERENCES [dbo].[ACC_CURRENCIES] ([CURRENCY_CODE_ALPHA3])
GO
