CREATE TABLE [dbo].[ACC_EVENT_TYPES]
(
[EVENT_TYPE_ID] [bigint] NOT NULL,
[EVENT_NAME] [nvarchar] (32) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ACC_EVENT_TYPES] ADD CONSTRAINT [ACC_EVENT_TYPES_PK] PRIMARY KEY CLUSTERED  ([EVENT_TYPE_ID]) ON [PRIMARY]
GO
