CREATE TABLE [dbo].[ACC_TRANSFER_FEES]
(
[TRANSFER_FEE_ID] [bigint] NOT NULL,
[ACCOUNT_GROUP_ID] [bigint] NOT NULL,
[TRANSFER_METHOD_ID] [bigint] NOT NULL,
[CURRENCY_CODE_ALPHA3] [char] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[AMOUNT_MINOR_UNITS_OUT] [bigint] NOT NULL,
[AMOUNT_MINOR_UNITS_IN] [bigint] NOT NULL,
[AMOUNT_MINOR_UNITS_OUT_ADD] [bigint] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ACC_TRANSFER_FEES] ADD CONSTRAINT [ACC_TRANSFER_FEES_PK] PRIMARY KEY CLUSTERED  ([TRANSFER_FEE_ID]) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [ACC_TRANSFER_FEES_IDX] ON [dbo].[ACC_TRANSFER_FEES] ([ACCOUNT_GROUP_ID], [TRANSFER_METHOD_ID], [CURRENCY_CODE_ALPHA3]) WITH (PAD_INDEX=ON) ON [INDEX]
GO
ALTER TABLE [dbo].[ACC_TRANSFER_FEES] WITH NOCHECK ADD CONSTRAINT [ACC_TRANS_FEE_ACCOUNT_GROUP_FK] FOREIGN KEY ([ACCOUNT_GROUP_ID]) REFERENCES [dbo].[ACC_ACCOUNT_GROUPS] ([ACCOUNT_GROUP_ID])
GO
ALTER TABLE [dbo].[ACC_TRANSFER_FEES] WITH NOCHECK ADD CONSTRAINT [ACC_TRANS_FEE_XFER_METHOD_FK] FOREIGN KEY ([TRANSFER_METHOD_ID]) REFERENCES [dbo].[ACC_TRANSFER_METHODS] ([TRANSFER_METHOD_ID])
GO
