CREATE TABLE [dbo].[ACC_SALE_DETAILS]
(
[TRANSACTION_ID] [bigint] NOT NULL,
[SALE_CLASS_ID] [bigint] NOT NULL,
[REGIONALITY] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[CARD_TYPE_ID] [bigint] NOT NULL,
[ACQUIRER_ID] [bigint] NOT NULL,
[CART_ID] [nvarchar] (512) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ACC_SALE_DETAILS] ADD CONSTRAINT [ACC_SALE_DETAILS_PK] PRIMARY KEY CLUSTERED  ([TRANSACTION_ID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [ACC_SALE_DETAIL_CT_FI] ON [dbo].[ACC_SALE_DETAILS] ([CARD_TYPE_ID]) WITH (PAD_INDEX=ON) ON [INDEX]
GO
CREATE NONCLUSTERED INDEX [ACC_SALE_DETAIL_SC_FI] ON [dbo].[ACC_SALE_DETAILS] ([SALE_CLASS_ID]) WITH (PAD_INDEX=ON) ON [INDEX]
GO
ALTER TABLE [dbo].[ACC_SALE_DETAILS] WITH NOCHECK ADD CONSTRAINT [ACC_SALE_DETAIL_CARD_TYPES_FK] FOREIGN KEY ([CARD_TYPE_ID]) REFERENCES [dbo].[ACC_CARD_TYPES] ([CARD_TYPE_ID]) ON DELETE CASCADE
GO
ALTER TABLE [dbo].[ACC_SALE_DETAILS] WITH NOCHECK ADD CONSTRAINT [ACC_SALE_DETAIL_SALE_CLASS_FK] FOREIGN KEY ([SALE_CLASS_ID]) REFERENCES [dbo].[ACC_SALE_CLASSES] ([SALE_CLASS_ID]) ON DELETE CASCADE
GO
