CREATE TABLE [dbo].[ACC_TRANSACTION_MARGIN_TYPES]
(
[TYPE_ID] [bigint] NOT NULL,
[DESCRIPTION] [nvarchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ACC_TRANSACTION_MARGIN_TYPES] ADD CONSTRAINT [ACC_TRANS_MARGIN_TYPES_PK] PRIMARY KEY CLUSTERED  ([TYPE_ID]) ON [PRIMARY]
GO
