CREATE TABLE [dbo].[CST_DESIGNATOR_TYPES]
(
[TYPE_ID] [bigint] NOT NULL,
[DESCRIPTION] [nvarchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[CATEGORY_ID] [bigint] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CST_DESIGNATOR_TYPES] ADD CONSTRAINT [CST_DESIGNATOR_TYPES_PK] PRIMARY KEY CLUSTERED  ([TYPE_ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CST_DESIGNATOR_TYPES] WITH NOCHECK ADD CONSTRAINT [CST_DESIGNATOR_TP_FK] FOREIGN KEY ([TYPE_ID]) REFERENCES [dbo].[CST_DESIGNATOR_TYPES] ([TYPE_ID])
GO
ALTER TABLE [dbo].[CST_DESIGNATOR_TYPES] WITH NOCHECK ADD CONSTRAINT [CST_DESIGNATOR_TYPES_CAT_FK] FOREIGN KEY ([CATEGORY_ID]) REFERENCES [dbo].[CST_DESIGNATOR_CATEGORIES] ([CATEGORY_ID])
GO
