CREATE TABLE [dbo].[ACC_PRELOAD_DESTINATION]
(
[OWNER_ID] [bigint] NOT NULL CONSTRAINT [DF_ACC_PRELOAD_DESTINATION_OWNER_ID] DEFAULT ((0)),
[CURRENCY_CODE_ALPHA3] [char] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[DESTINATION_ACCOUNT_GROUP_ID] [bigint] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ACC_PRELOAD_DESTINATION] ADD CONSTRAINT [ACC_PRE_DESTINATION_PK] PRIMARY KEY CLUSTERED  ([OWNER_ID], [CURRENCY_CODE_ALPHA3]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ACC_PRELOAD_DESTINATION] WITH NOCHECK ADD CONSTRAINT [ACC_PRE_DESTINATION_AG_FK] FOREIGN KEY ([DESTINATION_ACCOUNT_GROUP_ID]) REFERENCES [dbo].[ACC_ACCOUNT_GROUPS] ([ACCOUNT_GROUP_ID])
GO
ALTER TABLE [dbo].[ACC_PRELOAD_DESTINATION] WITH NOCHECK ADD CONSTRAINT [ACC_PRE_DESTINATION_CUR_FK] FOREIGN KEY ([CURRENCY_CODE_ALPHA3]) REFERENCES [dbo].[ACC_CURRENCIES] ([CURRENCY_CODE_ALPHA3])
GO
ALTER TABLE [dbo].[ACC_PRELOAD_DESTINATION] WITH NOCHECK ADD CONSTRAINT [ACC_PRE_DESTINATION_OWNER_FK] FOREIGN KEY ([OWNER_ID]) REFERENCES [dbo].[ACC_OWNERS] ([OWNER_ID])
GO
