CREATE TABLE [dbo].[ACC_COUNTRY_MONITORS]
(
[MONITOR_ID] [bigint] NOT NULL,
[COUNTRY_ID] [bigint] NOT NULL,
[DESCRIPTION] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CREATION_DATE] [datetime2] (6) NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ACC_COUNTRY_MONITORS] ADD CONSTRAINT [ACC_COUNTRY_PAY_MON_PK] PRIMARY KEY CLUSTERED  ([MONITOR_ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ACC_COUNTRY_MONITORS] ADD CONSTRAINT [ACC_COUNTRY_MONITORS_UI] UNIQUE NONCLUSTERED  ([COUNTRY_ID]) ON [INDEX]
GO
ALTER TABLE [dbo].[ACC_COUNTRY_MONITORS] WITH NOCHECK ADD CONSTRAINT [ACC_COUNTRIES_FK] FOREIGN KEY ([COUNTRY_ID]) REFERENCES [dbo].[ACC_COUNTRIES] ([COUNTRY_ID])
GO
