CREATE TABLE [dbo].[ACC_COUNTRIES]
(
[COUNTRY_ID] [bigint] NOT NULL,
[COUNTRY_CODE_ALPHA2] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[COUNTRY_CODE_ALPHA3] [char] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[COUNTRY_CODE] [bigint] NULL,
[REGION_CODE] [char] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[COUNTRY_NAME] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TIMEZONE] [bigint] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ACC_COUNTRIES] ADD CONSTRAINT [ACC_COUNTRIES_PK] PRIMARY KEY CLUSTERED  ([COUNTRY_ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ACC_COUNTRIES] ADD CONSTRAINT [ACC_COUNTRIES_ALPHA2_UI] UNIQUE NONCLUSTERED  ([COUNTRY_CODE_ALPHA2]) ON [INDEX]
GO
ALTER TABLE [dbo].[ACC_COUNTRIES] ADD CONSTRAINT [ACC_COUNTRIES_ALPHA3_UI] UNIQUE NONCLUSTERED  ([COUNTRY_CODE_ALPHA3]) ON [INDEX]
GO
