CREATE TABLE [dbo].[ACC_MONEYCORP_RETURNS]
(
[MONEYCORP_RETURN_ID] [bigint] NOT NULL,
[RECEIVED_TIME] [datetime2] (6) NULL,
[PROCESSED_TIME] [datetime2] (6) NULL,
[PAYMENT_REF] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MONEYCORP_PAYMENT_REF] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AMOUNT] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PAYMENT_CHANNEL_ID] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CLIENT_REF] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PAYMENT_DATE] [datetime2] (0) NULL,
[REFERENCE_KEY] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ALLOCATED_AMOUNT] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[REFERENCE_7] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[REFERENCE_8] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RIGHT_CLIENT_FUND_LINE_ID] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RIGHT_AMOUNT] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RIGHT_CLIENT_REF] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RIGHT_PAYMENT_DATE] [datetime2] (0) NULL,
[RIGHT_REFERENCE_KEY] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RIGHT_ALLOCATED_AMOUNT] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[REGEX_OUT_1] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[REGEX_OUT_2] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ORIGINAL_PAYMENT_REF] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SHORTFALL] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ACC_MONEYCORP_RETURNS] ADD CONSTRAINT [ACC_MONEYCORP_RETURNS_PK] PRIMARY KEY CLUSTERED  ([MONEYCORP_RETURN_ID]) ON [PRIMARY]
GO
