CREATE TABLE [dbo].[ACC_FUNDS_REQUESTS]
(
[FUNDS_REQUEST_ID] [bigint] NOT NULL,
[REQUEST_TIME] [datetime2] (6) NOT NULL,
[PAYER_NAME] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PAYER_EMAIL] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[AMOUNT_MINOR_UNITS] [bigint] NOT NULL,
[REQUEST_REASON] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[REQUEST_REFERENCE] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[TRANSACTION_ID] [bigint] NULL,
[PAID_STATUS] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_ACC_FUNDS_REQUESTS_PAID_STATUS] DEFAULT ('N'),
[ACCOUNT_GROUP_ID] [bigint] NULL,
[TARGET_ACCOUNT_GROUP_ID] [bigint] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ACC_FUNDS_REQUESTS] ADD CONSTRAINT [ACC_FUNDS_REQUESTS_PK] PRIMARY KEY CLUSTERED  ([FUNDS_REQUEST_ID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [ACC_FUNDS_REQUESTS_IN] ON [dbo].[ACC_FUNDS_REQUESTS] ([ACCOUNT_GROUP_ID], [REQUEST_REFERENCE]) WITH (PAD_INDEX=ON) ON [INDEX]
GO
ALTER TABLE [dbo].[ACC_FUNDS_REQUESTS] WITH NOCHECK ADD CONSTRAINT [ACC_FUNDS_REQUESTS_AG_ID_FK] FOREIGN KEY ([ACCOUNT_GROUP_ID]) REFERENCES [dbo].[ACC_ACCOUNT_GROUPS] ([ACCOUNT_GROUP_ID])
GO
ALTER TABLE [dbo].[ACC_FUNDS_REQUESTS] WITH NOCHECK ADD CONSTRAINT [ACC_FUNDS_REQUESTS_TAG_ID_FK] FOREIGN KEY ([TARGET_ACCOUNT_GROUP_ID]) REFERENCES [dbo].[ACC_ACCOUNT_GROUPS] ([ACCOUNT_GROUP_ID])
GO
