CREATE TABLE [dbo].[ACC_CURRENCIES]
(
[CURRENCY_CODE_ALPHA3] [char] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[DECIMAL_PLACES] [numeric] (38, 0) NOT NULL,
[DEFAULT_REMITTANCE_THRESHOLD_MINOR_UNIT] [bigint] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ACC_CURRENCIES] ADD CONSTRAINT [ACC_CURRENCIES_PK] PRIMARY KEY CLUSTERED  ([CURRENCY_CODE_ALPHA3]) ON [PRIMARY]
GO
