CREATE TABLE [dbo].[DATABASECHANGELOGLOCK]
(
[ID] [int] NOT NULL,
[LOCKED] [bit] NOT NULL,
[LOCKGRANTED] [datetime2] (3) NULL,
[LOCKEDBY] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[DATABASECHANGELOGLOCK] ADD CONSTRAINT [PK_DATABASECHANGELOGLOCK] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
