CREATE TABLE [dbo].[ACC_CARD_CATEGORIES]
(
[CARD_CATEGORY_CODE] [nvarchar] (7) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[NAME] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ACC_CARD_CATEGORIES] ADD CONSTRAINT [ACC_CARD_CATEGORY_PK] PRIMARY KEY CLUSTERED  ([CARD_CATEGORY_CODE]) ON [PRIMARY]
GO
