CREATE TABLE [dbo].[ACC_PAYMENT_SOURCES]
(
[BULK_PAYMENT_SOURCE_ID] [bigint] NOT NULL,
[BULK_PAYMENT_SOURCE_NAME] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ACC_PAYMENT_SOURCES] ADD CONSTRAINT [BULK_PAYMENT_SOURCE_ID_PK] PRIMARY KEY CLUSTERED  ([BULK_PAYMENT_SOURCE_ID]) ON [PRIMARY]
GO
