CREATE TABLE [dbo].[ACC_PRICING_REGIONS_REGIONS]
(
[PRICING_REGION_CODE] [nvarchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[REGION_CODE] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ACC_PRICING_REGIONS_REGIONS] ADD CONSTRAINT [PK_ACC_PRICING_RGNS_RGNS] PRIMARY KEY CLUSTERED  ([PRICING_REGION_CODE], [REGION_CODE]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ACC_PRICING_REGIONS_REGIONS] WITH NOCHECK ADD CONSTRAINT [ACC_PR_REG_REG_PR_REG_FK] FOREIGN KEY ([PRICING_REGION_CODE]) REFERENCES [dbo].[ACC_PRICING_REGIONS] ([PRICING_REGION_CODE])
GO
ALTER TABLE [dbo].[ACC_PRICING_REGIONS_REGIONS] WITH NOCHECK ADD CONSTRAINT [ACC_PR_REG_REG_REG_FK] FOREIGN KEY ([REGION_CODE]) REFERENCES [dbo].[ACC_REGIONS] ([REGION_CODE])
GO
