CREATE TABLE [dbo].[ACC_MONTHLY_ALLOWANCES]
(
[MONTHLY_ALLOWANCE_ID] [bigint] NOT NULL,
[TRANSFER_METHOD_ID] [bigint] NOT NULL,
[FREE_ALLOWANCE] [bigint] NOT NULL,
[ACCOUNT_GROUP_ID] [bigint] NULL,
[REMAINING_UNITS] [bigint] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ACC_MONTHLY_ALLOWANCES] ADD CONSTRAINT [ACC_MONTHLY_ALLOWANCES_PK] PRIMARY KEY CLUSTERED  ([MONTHLY_ALLOWANCE_ID]) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [ACC_MONTHLY_ALLOWANCES_IDX] ON [dbo].[ACC_MONTHLY_ALLOWANCES] ([ACCOUNT_GROUP_ID], [TRANSFER_METHOD_ID]) WITH (PAD_INDEX=ON) ON [INDEX]
GO
ALTER TABLE [dbo].[ACC_MONTHLY_ALLOWANCES] WITH NOCHECK ADD CONSTRAINT [ACC_MONTH_ALLOW_ACC_GROUP_FK] FOREIGN KEY ([ACCOUNT_GROUP_ID]) REFERENCES [dbo].[ACC_ACCOUNT_GROUPS] ([ACCOUNT_GROUP_ID])
GO
ALTER TABLE [dbo].[ACC_MONTHLY_ALLOWANCES] WITH NOCHECK ADD CONSTRAINT [ACC_MONTH_ALLOW_XFER_TYPE_FK] FOREIGN KEY ([TRANSFER_METHOD_ID]) REFERENCES [dbo].[ACC_TRANSFER_METHODS] ([TRANSFER_METHOD_ID])
GO
