CREATE TABLE [dbo].[ACC_PRICING_TURNOVER_BANDS]
(
[DESCRIPTION] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[PRICING_TURNOVER_BAND_ID] [bigint] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ACC_PRICING_TURNOVER_BANDS] ADD CONSTRAINT [ACC_PRICING_TURNOVER_BANDS_PK] PRIMARY KEY CLUSTERED  ([PRICING_TURNOVER_BAND_ID]) ON [PRIMARY]
GO
