CREATE TABLE [dbo].[ACC_CONCURRENT_REPORTS]
(
[REPORT_NAME] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[TIME_ADDED] [datetime2] (0) NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ACC_CONCURRENT_REPORTS] ADD CONSTRAINT [ACC_RPTING_CNC_RPS_PK] PRIMARY KEY CLUSTERED  ([REPORT_NAME]) ON [PRIMARY]
GO
