CREATE TABLE [dbo].[ACC_PROCESSOR_RECORDS]
(
[ACC_PROCESSOR_ID] [bigint] NOT NULL,
[PROCESSOR_NAME] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[PROCESS_TIMESTAMP] [datetime2] (6) NULL,
[USERNAME] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PROCESS_LOG] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ACC_PROCESSOR_RECORDS] ADD CONSTRAINT [ACC_PROCESSOR_RECORD_PK] PRIMARY KEY CLUSTERED  ([ACC_PROCESSOR_ID]) ON [PRIMARY]
GO
