CREATE TABLE [dbo].[ACC_TRANSACTIONS]
(
[TRANSACTION_ID] [bigint] NOT NULL,
[EVENT_TYPE_ID] [bigint] NOT NULL,
[TRANSACTION_TIME] [datetime2] (6) NOT NULL,
[DESCRIPTION] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AMOUNT_MINOR_UNITS] [bigint] NOT NULL,
[ACCOUNT_GROUP_ID] [bigint] NOT NULL,
[TXN_FIRST_ID] [bigint] NULL,
[EXTERNAL_REF] [nvarchar] (23) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TXN_GROUP_ID] [nvarchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[USER_NAME] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SOURCE_REF] [nvarchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CUSTOMER_REF] [nvarchar] (512) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CURRENCY] [char] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EXCHANGE_RATE] [numeric] (12, 5) NULL,
[TXN_ASSOCIATION_ID] [bigint] NULL,
[BUY_FIXED_AMOUNT_MINOR_UNIT] [numeric] (18, 0) NULL CONSTRAINT [DF_ACC_TRANSACTIONS_BUY_FIXED_AMOUNT_MINOR_UNIT] DEFAULT ((0)),
[BUY_VARIABLE_PERCENTAGE] [numeric] (18, 2) NULL CONSTRAINT [DF_ACC_TRANSACTIONS_BUY_VARIABLE_PERCENTAGE] DEFAULT ((0)),
[SELL_FIXED_AMOUNT_MINOR_UNIT] [numeric] (18, 0) NULL CONSTRAINT [DF_ACC_TRANSACTIONS_SELL_FIXED_AMOUNT_MINOR_UNIT] DEFAULT ((0)),
[SELL_VARIABLE_PERCENTAGE] [numeric] (18, 2) NULL CONSTRAINT [DF_ACC_TRANSACTIONS_SELL_VARIABLE_PERCENTAGE] DEFAULT ((0))
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ACC_TRANSACTIONS] ADD CONSTRAINT [ACC_TRANSACTIONS_PK] PRIMARY KEY CLUSTERED  ([TRANSACTION_ID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [ACC_TRANS_ACC_GROUP_FI] ON [dbo].[ACC_TRANSACTIONS] ([ACCOUNT_GROUP_ID]) WITH (PAD_INDEX=ON) ON [INDEX]
GO
CREATE NONCLUSTERED INDEX [ACC_TRANS_EVENT_TYPE_FI] ON [dbo].[ACC_TRANSACTIONS] ([EVENT_TYPE_ID]) WITH (PAD_INDEX=ON) ON [INDEX]
GO
CREATE UNIQUE NONCLUSTERED INDEX [ACC_TRANS_EXTREF_UI] ON [dbo].[ACC_TRANSACTIONS] ([EXTERNAL_REF], [EVENT_TYPE_ID]) WHERE ([EXTERNAL_REF] IS NOT NULL) WITH (PAD_INDEX=ON) ON [INDEX]
GO
CREATE NONCLUSTERED INDEX [ACC_TRANSACTIONS_TXN_TIME] ON [dbo].[ACC_TRANSACTIONS] ([TRANSACTION_TIME]) INCLUDE ([ACCOUNT_GROUP_ID], [AMOUNT_MINOR_UNITS], [EVENT_TYPE_ID], [SOURCE_REF], [TRANSACTION_ID], [TXN_FIRST_ID]) ON [INDEX]
GO
CREATE NONCLUSTERED INDEX [ACC_TRANSACTIONS_MERCH_TURNOVER_RPT] ON [dbo].[ACC_TRANSACTIONS] ([TRANSACTION_TIME]) INCLUDE ([ACCOUNT_GROUP_ID], [EVENT_TYPE_ID], [SOURCE_REF], [TRANSACTION_ID], [TXN_FIRST_ID]) ON [INDEX]
GO
CREATE NONCLUSTERED INDEX [ACC_TXN_ASSOCIATION_ID] ON [dbo].[ACC_TRANSACTIONS] ([TXN_ASSOCIATION_ID]) INCLUDE ([ACCOUNT_GROUP_ID], [AMOUNT_MINOR_UNITS], [EVENT_TYPE_ID], [TRANSACTION_ID]) ON [INDEX]
GO
CREATE NONCLUSTERED INDEX [ACC_TRANS_TXN_FIRST_FI] ON [dbo].[ACC_TRANSACTIONS] ([TXN_FIRST_ID]) WITH (PAD_INDEX=ON) ON [INDEX]
GO
ALTER TABLE [dbo].[ACC_TRANSACTIONS] WITH NOCHECK ADD CONSTRAINT [ACC_TRANSACTION_EVENT_TYPE_FK] FOREIGN KEY ([EVENT_TYPE_ID]) REFERENCES [dbo].[ACC_EVENT_TYPES] ([EVENT_TYPE_ID])
GO
ALTER TABLE [dbo].[ACC_TRANSACTIONS] WITH NOCHECK ADD CONSTRAINT [ACC_TRANSACTIONS_ACC_GROUP_FK] FOREIGN KEY ([ACCOUNT_GROUP_ID]) REFERENCES [dbo].[ACC_ACCOUNT_GROUPS] ([ACCOUNT_GROUP_ID])
GO
