CREATE TABLE [dbo].[ACC_HSBC_ACCOUNT_MAPPINGS]
(
[ACCOUNT_MAPPING_ID] [bigint] NOT NULL,
[CURRENCY_CODE_ALPHA3] [char] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[SORT_CODE] [nvarchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TRANSFER_TYPE_ID] [bigint] NULL,
[TRANSFER_METHOD_ID] [bigint] NULL,
[ACCOUNT_ID] [bigint] NOT NULL,
[INCL_EXCL] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_ACC_HSBC_ACCOUNT_MAPPINGS_INCL_EXCL] DEFAULT ('I')
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ACC_HSBC_ACCOUNT_MAPPINGS] ADD CONSTRAINT [ACCOUNT_MAPPING_ID_PK] PRIMARY KEY CLUSTERED  ([ACCOUNT_MAPPING_ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ACC_HSBC_ACCOUNT_MAPPINGS] WITH NOCHECK ADD CONSTRAINT [HSBC_ACCOUNT_MAPPING_AC_FK] FOREIGN KEY ([ACCOUNT_ID]) REFERENCES [dbo].[ACC_HSBC_ACCOUNTS] ([ACCOUNT_ID])
GO
ALTER TABLE [dbo].[ACC_HSBC_ACCOUNT_MAPPINGS] WITH NOCHECK ADD CONSTRAINT [HSBC_ACCOUNT_MAPPING_CURR_FK] FOREIGN KEY ([CURRENCY_CODE_ALPHA3]) REFERENCES [dbo].[ACC_CURRENCIES] ([CURRENCY_CODE_ALPHA3])
GO
ALTER TABLE [dbo].[ACC_HSBC_ACCOUNT_MAPPINGS] WITH NOCHECK ADD CONSTRAINT [HSBC_ACCOUNT_MAPPING_TM_FK] FOREIGN KEY ([TRANSFER_METHOD_ID]) REFERENCES [dbo].[ACC_TRANSFER_METHODS] ([TRANSFER_METHOD_ID])
GO
ALTER TABLE [dbo].[ACC_HSBC_ACCOUNT_MAPPINGS] WITH NOCHECK ADD CONSTRAINT [HSBC_ACCOUNT_MAPPING_TT_FK] FOREIGN KEY ([TRANSFER_TYPE_ID]) REFERENCES [dbo].[ACC_TRANSFER_TYPES] ([TRANSFER_TYPE_ID])
GO
