CREATE TABLE [dbo].[ACC_ACQUIRING_FEES_IC]
(
[ACQ_FEE_IC_ID] [bigint] NOT NULL CONSTRAINT [ACC_ACQUIRING_FEES_IC_DEFAULT] DEFAULT (NEXT VALUE FOR [dbo].[ACQUIRING_FEE_SEQUENCE]),
[ACCOUNT_GROUP_ID] [bigint] NOT NULL,
[FEE_DISTINGUISHER] [nvarchar] (48) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_ACC_ACQUIRING_FEES_IC_FEE_DISTINGUISHER] DEFAULT ('N/A'),
[AMOUNT_MINOR_UNITS] [bigint] NOT NULL,
[PERCENTAGE] [decimal] (18, 2) NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ACC_ACQUIRING_FEES_IC] ADD CONSTRAINT [ACC_ACQ_FEE_IC_PK] PRIMARY KEY CLUSTERED  ([ACQ_FEE_IC_ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ACC_ACQUIRING_FEES_IC] WITH NOCHECK ADD CONSTRAINT [ACC_ACQ_FEES_IC_AG_PK] FOREIGN KEY ([ACCOUNT_GROUP_ID]) REFERENCES [dbo].[ACC_ACCOUNT_GROUPS] ([ACCOUNT_GROUP_ID])
GO
