CREATE TABLE [dbo].[ACC_PRICING_TURNOVER_ALIASES]
(
[PRICING_TURNOVER_BAND_ALIAS] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[PRICING_TURNOVER_BAND_ID] [bigint] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ACC_PRICING_TURNOVER_ALIASES] ADD CONSTRAINT [ACC_PRICING_TURNOVER_ALIAS_PK] PRIMARY KEY CLUSTERED  ([PRICING_TURNOVER_BAND_ALIAS]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ACC_PRICING_TURNOVER_ALIASES] WITH NOCHECK ADD CONSTRAINT [ACC_PRICING_TURNOVER_FK] FOREIGN KEY ([PRICING_TURNOVER_BAND_ID]) REFERENCES [dbo].[ACC_PRICING_TURNOVER_BANDS] ([PRICING_TURNOVER_BAND_ID])
GO
