CREATE TABLE [dbo].[ACC_COMMISSION_POINTS]
(
[POINT_ID] [bigint] NOT NULL,
[EVENT_TYPE_ID] [bigint] NOT NULL,
[FEE_DISTINGUISHER] [nvarchar] (48) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FIXED_AMOUNT_MINOR_UNITS] [bigint] NULL,
[FIXED_CURRENCY_CODE_ALPHA3] [char] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[VARIABLE_PERCENTAGE] [decimal] (18, 4) NULL,
[COMMISSION_PLAN_ID] [bigint] NOT NULL,
[SPLIT_PERCENTAGE] [decimal] (18, 2) NULL,
[SCHEME_REGION_CODE] [nvarchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ACC_COMMISSION_POINTS] ADD CONSTRAINT [ACC_COMMISSION_POINTS_PK] PRIMARY KEY CLUSTERED  ([POINT_ID]) ON [PRIMARY]
GO
