CREATE TABLE [dbo].[ACC_ACCOUNTS]
(
[ACCOUNT_ID] [bigint] NOT NULL,
[ACCOUNT_GROUP_ID] [bigint] NOT NULL,
[ACCOUNT_TYPE_ID] [bigint] NOT NULL,
[BALANCE_MINOR_UNITS] [bigint] NOT NULL,
[MATURITY_HOURS] [bigint] NULL,
[MATURITY_MODEL] [tinyint] NOT NULL CONSTRAINT [MATURITY_MODEL_DEFAULT] DEFAULT ((0))
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ACC_ACCOUNTS] ADD CONSTRAINT [ACC_ACCOUNTS_PK] PRIMARY KEY CLUSTERED  ([ACCOUNT_ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ACC_ACCOUNTS] ADD CONSTRAINT [ACC_ACCOUNT_JOIN_UI] UNIQUE NONCLUSTERED  ([ACCOUNT_GROUP_ID], [ACCOUNT_TYPE_ID]) ON [INDEX]
GO
CREATE NONCLUSTERED INDEX [ACC_ACCOUNT_GROUP_TYPE_BALANCE] ON [dbo].[ACC_ACCOUNTS] ([ACCOUNT_GROUP_ID], [ACCOUNT_TYPE_ID]) INCLUDE ([BALANCE_MINOR_UNITS], [MATURITY_HOURS]) ON [INDEX]
GO
CREATE NONCLUSTERED INDEX [ACC_ACCOUNTS_FI] ON [dbo].[ACC_ACCOUNTS] ([ACCOUNT_TYPE_ID]) WITH (PAD_INDEX=ON) ON [INDEX]
GO
ALTER TABLE [dbo].[ACC_ACCOUNTS] WITH NOCHECK ADD CONSTRAINT [ACC_ACCOUNT_ACCOUNT_GROUP_FK] FOREIGN KEY ([ACCOUNT_GROUP_ID]) REFERENCES [dbo].[ACC_ACCOUNT_GROUPS] ([ACCOUNT_GROUP_ID]) ON DELETE CASCADE
GO
ALTER TABLE [dbo].[ACC_ACCOUNTS] WITH NOCHECK ADD CONSTRAINT [ACC_ACCOUNT_ACCOUNT_TYPE_FK] FOREIGN KEY ([ACCOUNT_TYPE_ID]) REFERENCES [dbo].[ACC_ACCOUNT_TYPES] ([ACCOUNT_TYPE_ID])
GO
