CREATE TABLE [dbo].[tlkpCostVisaInterchangeFee]
(
[FeeId] [bigint] NOT NULL IDENTITY(1, 1),
[EffectiveFrom] [datetime2] NULL,
[EffectiveUntil] [datetime2] NULL,
[MerchantCountryRegion] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IssuerCountryRegion] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FeeScenario] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MinimumAmountMajorUnit] [decimal] (18, 2) NULL,
[MaximumAmountMajorUnit] [decimal] (18, 2) NULL,
[AmountCurrency] [nchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Afs] [nchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Pid] [nchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ProductSubtype] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ProductType] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FeeDescriptor] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FeePercentAsMultiplier] [decimal] (18, 8) NULL,
[FixedFeeMajorUnit] [decimal] (18, 8) NULL,
[CappedMajorUnit] [decimal] (18, 8) NULL,
[FixedCurrency] [nchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Fpi] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ReimbAttr] [nchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CardCapabilityFlag] [nchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PosTerminalCapability] [nchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AuthCode] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PosEntryMode] [nchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CardholderIdMethod] [nchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MotoEci] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MccSpecific] [nchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ExcludingMccs] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PosEnvCode] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Ati] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AuthRespCode] [nchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CvvResult] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TimelinessDays] [bigint] NULL,
[ChipTerminalDeploymentFLag] [nchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BusinessApplicationIdentifier] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AuthCharac] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RequestedPaymentService] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Dcci] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[tlkpCostVisaInterchangeFee] ADD CONSTRAINT [PK_tlkpCostVisaInterchangeFee] PRIMARY KEY CLUSTERED  ([FeeId]) ON [PRIMARY]
GO
