CREATE TABLE [dbo].[ACC_PRICING_TIER_ALLOWANCES]
(
[TIER_ALLOWANCE_ID] [bigint] NOT NULL CONSTRAINT [ACC_PRICING_TIER_ALLOWANCES_DEFAULT] DEFAULT (NEXT VALUE FOR [dbo].[PRICING_TIER_ALLOW_SEQUENCE]),
[PRICING_TIER_ID] [bigint] NOT NULL,
[TRANSFER_METHOD_ID] [bigint] NOT NULL,
[FREE_ALLOWANCE] [bigint] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ACC_PRICING_TIER_ALLOWANCES] ADD CONSTRAINT [ACC_PRICING_TIER_ALLOWANCES_PK] PRIMARY KEY CLUSTERED  ([TIER_ALLOWANCE_ID]) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [ACC_TIER_ALLOWANCES_IDX] ON [dbo].[ACC_PRICING_TIER_ALLOWANCES] ([PRICING_TIER_ID], [TRANSFER_METHOD_ID]) WITH (PAD_INDEX=ON) ON [INDEX]
GO
ALTER TABLE [dbo].[ACC_PRICING_TIER_ALLOWANCES] WITH NOCHECK ADD CONSTRAINT [ACC_TIER_ALLOW_PRICING_TIER_FK] FOREIGN KEY ([PRICING_TIER_ID]) REFERENCES [dbo].[ACC_PRICING_TIERS] ([PRICING_TIER_ID])
GO
ALTER TABLE [dbo].[ACC_PRICING_TIER_ALLOWANCES] WITH NOCHECK ADD CONSTRAINT [ACC_TIER_ALLOW_XFER_METHOD_FK] FOREIGN KEY ([TRANSFER_METHOD_ID]) REFERENCES [dbo].[ACC_TRANSFER_METHODS] ([TRANSFER_METHOD_ID])
GO
