CREATE TABLE [dbo].[ACC_HSBC_ACCOUNT_BALANCES]
(
[BALANCE_ID] [bigint] NOT NULL,
[ACCOUNT_ID] [bigint] NOT NULL,
[BALANCE_DATE] [datetime2] (0) NOT NULL,
[OPENING_BALANCE_MINOR_UNITS] [bigint] NOT NULL,
[CLOSING_BALANCE_MINOR_UNITS] [bigint] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ACC_HSBC_ACCOUNT_BALANCES] ADD CONSTRAINT [ACC_HSBC_ACCT_BAL_PK] PRIMARY KEY CLUSTERED  ([BALANCE_ID]) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [HSBC_ACCOUNT_BAL_UI] ON [dbo].[ACC_HSBC_ACCOUNT_BALANCES] ([ACCOUNT_ID], [BALANCE_DATE]) WITH (PAD_INDEX=ON) ON [INDEX]
GO
ALTER TABLE [dbo].[ACC_HSBC_ACCOUNT_BALANCES] WITH NOCHECK ADD CONSTRAINT [ACC_HSBC_ACCT_BAL_ACCT_FK] FOREIGN KEY ([ACCOUNT_ID]) REFERENCES [dbo].[ACC_HSBC_ACCOUNTS] ([ACCOUNT_ID])
GO
