CREATE TABLE [dbo].[ACC_TRANSFERS]
(
[TRANSFER_ID] [bigint] NOT NULL,
[TRANSFER_TIME] [datetime2] (6) NOT NULL,
[ACCOUNT_ID] [bigint] NOT NULL,
[TRANSFER_TYPE_ID] [bigint] NOT NULL,
[AMOUNT_MINOR_UNITS] [bigint] NOT NULL,
[BALANCE_AFTER_MINOR_UNITS] [bigint] NOT NULL,
[BATCH_ID] [bigint] NULL,
[TRANSACTION_ID] [bigint] NOT NULL,
[TRANSFER_METHOD_ID] [bigint] NOT NULL CONSTRAINT [DF_ACC_TRANSFERS_TRANSFER_METHOD_ID] DEFAULT ((4)),
[MATURITY_TIME] [datetime2] NULL,
[MATURITY_TRANSACTION_ID] [bigint] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ACC_TRANSFERS] ADD CONSTRAINT [ACC_TRANSFERS_PK] PRIMARY KEY CLUSTERED  ([TRANSFER_ID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [ACC_TRANSFERS_ACCOUNT_ID_BATCH_ID] ON [dbo].[ACC_TRANSFERS] ([ACCOUNT_ID]) INCLUDE ([BATCH_ID]) ON [INDEX]
GO
CREATE NONCLUSTERED INDEX [IX_ACC_TRANSFERS_ACCOUNT_ID_MATURITY_TIME_MATURITY_TRANSACTION_ID] ON [dbo].[ACC_TRANSFERS] ([ACCOUNT_ID], [MATURITY_TIME], [MATURITY_TRANSACTION_ID]) INCLUDE ([AMOUNT_MINOR_UNITS]) ON [INDEX]
GO
CREATE NONCLUSTERED INDEX [ACC_TFS_TFXTIME_ACNTID] ON [dbo].[ACC_TRANSFERS] ([ACCOUNT_ID], [TRANSFER_TIME]) INCLUDE ([AMOUNT_MINOR_UNITS], [BALANCE_AFTER_MINOR_UNITS], [BATCH_ID], [TRANSACTION_ID], [TRANSFER_ID], [TRANSFER_METHOD_ID], [TRANSFER_TYPE_ID]) ON [INDEX]
GO
CREATE NONCLUSTERED INDEX [IX_ACC_TRANSFERS_ACCOUNT_ID_MATURITY_TRANSACTION_ID] ON [dbo].[ACC_TRANSFERS] ([MATURITY_TRANSACTION_ID], [ACCOUNT_ID]) ON [INDEX]
GO
CREATE NONCLUSTERED INDEX [ACC_TRANS_TXN_ID_FI] ON [dbo].[ACC_TRANSFERS] ([TRANSACTION_ID]) WITH (PAD_INDEX=ON) ON [INDEX]
GO
CREATE UNIQUE NONCLUSTERED INDEX [ACC_TRANSFERS_TXFR_TIME] ON [dbo].[ACC_TRANSFERS] ([TRANSFER_TIME], [ACCOUNT_ID], [TRANSFER_ID]) WITH (PAD_INDEX=ON) ON [INDEX]
GO
CREATE NONCLUSTERED INDEX [ACC_TRANS_TRAN_TYPE_ID_FI] ON [dbo].[ACC_TRANSFERS] ([TRANSFER_TYPE_ID]) WITH (PAD_INDEX=ON) ON [INDEX]
GO
CREATE NONCLUSTERED INDEX [ACC_TRANSFERS_MERCH_TURNOVER_RPT] ON [dbo].[ACC_TRANSFERS] ([TRANSFER_TYPE_ID], [AMOUNT_MINOR_UNITS]) INCLUDE ([TRANSACTION_ID]) ON [INDEX]
GO
ALTER TABLE [dbo].[ACC_TRANSFERS] WITH NOCHECK ADD CONSTRAINT [ACC_TRANSFERS_ACC_ID_FK] FOREIGN KEY ([ACCOUNT_ID]) REFERENCES [dbo].[ACC_ACCOUNTS] ([ACCOUNT_ID])
GO
ALTER TABLE [dbo].[ACC_TRANSFERS] WITH NOCHECK ADD CONSTRAINT [ACC_TRANSFERS_BATCH_ID_FK] FOREIGN KEY ([BATCH_ID]) REFERENCES [dbo].[ACC_BATCHES] ([BATCH_ID])
GO
ALTER TABLE [dbo].[ACC_TRANSFERS] WITH NOCHECK ADD CONSTRAINT [ACC_TRANSFERS_METHOD_ID_FK] FOREIGN KEY ([TRANSFER_METHOD_ID]) REFERENCES [dbo].[ACC_TRANSFER_METHODS] ([TRANSFER_METHOD_ID])
GO
ALTER TABLE [dbo].[ACC_TRANSFERS] WITH NOCHECK ADD CONSTRAINT [ACC_TRANSFERS_TRAN_TYPE_ID_FK] FOREIGN KEY ([TRANSFER_TYPE_ID]) REFERENCES [dbo].[ACC_TRANSFER_TYPES] ([TRANSFER_TYPE_ID])
GO
ALTER TABLE [dbo].[ACC_TRANSFERS] WITH NOCHECK ADD CONSTRAINT [ACC_TRANSFERS_TXN_ID_FK] FOREIGN KEY ([TRANSACTION_ID]) REFERENCES [dbo].[ACC_TRANSACTIONS] ([TRANSACTION_ID])
GO
