IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'NT AUTHORITY\SYSTEM')
CREATE LOGIN [NT AUTHORITY\SYSTEM] FROM WINDOWS
GO
CREATE USER [ServiceBrokerUser] FOR LOGIN [NT AUTHORITY\SYSTEM]
GO
